### PR TITLE
docs: remove unused assignement in Kubernetes tutorial example

### LINKED ISSUE #4778: Unused assignment in example Kubernetes policy
This policy example contains unused assignment: https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/#policy-1-restrict-hostnames

```rego
str_parts := split(str, ".")
n_pattern_parts := count(pattern_parts)
n_str_parts := count(str_parts)
```
Pasting the policy into the Rego playground and evaluating it with strict mode shows this. We should have those removed from the example.

### PR DESCRIPTION
**Pull request by Joffref**
Fixes #4778

### CODE REVIEW

**Review by anderseknert — DISMISSED** [review]
Thanks!

**Comment by anderseknert** [comment]
You'll need to provide a signoff for your commit before we can have this merged, i.e.

```shell
git commit --amend --signoff
git push --force
```

**Comment by Joffref** [comment]
Is this now okay for you ? @anderseknert 

Sorry for multiple commits, I'm starting at contributing open-sources project.

**Review by anderseknert — APPROVED** [review]

**Comment by anderseknert** [comment]
Looks great! Thanks for contributing 👍

**Pull request merged**
