### PR TITLE
DecisionLogs: Drop rule and Elastic log format

### PR DESCRIPTION
**Pull request by iamatwork**
Hello maintainers,

please have a careful look at my PR, because this is 100% of the Go-code I have written in my life. It works fine on my Kafka-dev-cluster. I'll give it some load tonight.

I tried to solved problems: 

### #3945  (Allow policy-based dropping of some decision log items)

New configuration option `decision_logs.drop_decision` (defaults to `/system/log/drop`) allows to write rules, that drop decisions before logging,.

e.g. drop all granted requests
`
package system.log

drop {
  input.result
}
`

### Log to ELK (elastic)

This allows to write decision logs directly to an ELK-cluster.

New configuration options 

- log format
  - `json` format used currently (default option)
  - `ndjson`  places each log entry in a new line. no json-array around the whole output.
  - `elastic` like ndjson, but before each line an elastic bulk-api command is inserted
- `elastic_index` sets the name of the index to write to. This might be different from the value specified in the URL.
- resource (not new) needs to point to `/index_name/_bulk` to ingest to ELK.

Bulk-API example
`
{"index":{"_index":"opa_decisions_alias","_type":"_doc","_id":"abc6c2a7-f614-489f-9e4e-d934e3c802c5"}}
{"actual":"log entry"}
`

I implemented that by replacing the hard-coded `[  ]` in logs.encoder with functions, that are set according to the configuration when creating a new instance.

`prefix` function is called before each log entry. For json returns `,` or `[` , if it is the first entry in the buffer.
Nothing or newline for ndjson.
Bulk-API statement with the decision_id as key (and newline) for format elastic.

`postfix` function is called before sending the buffer to the log-system.  (`]` for format json, newline for ndjson and elastic).

I think the reset mechanism for the buffer works, because the Bulk-API-lines are ignored during deserialization, but I lack the Go-skills to judge that.

### CODE REVIEW

**Comment by ashutosh-narkar** [comment]
Hello @iamatwork thanks for the contribution. This PR seems to implement two separate features, one around dropping logs and other around exporting them. It would be great if you could trim it down to the former and we can look at opening an issue for the latter and working on that separately. I think it would be good if the exporting log feature had its own issue with some design details and that would make it easier to iterate on. Thanks!

**Comment by iamatwork** [comment]
Hello @ashutosh-narkar,
I'll try to do that tomorrow. And to fix the LINT-errors I got.
Thanks.

**Comment by johanneslarsson** [comment]
@iamatwork Do you mind if I or a college of mine continue on this PR?

**Comment by iamatwork** [comment]
> @iamatwork Do you mind if I or a college of mine continue on this PR?

I'd be happy, if you did.

**Pull request merged**
