### PR TITLE
Fix aws Sigv4 signature

### LINKED ISSUE #4954: Incorrect AWS Sigv4 signature when specifying version of S3 object as URL Parameter
## Short description 

We are using opa's discovery feature to dynamically download s3 bundles. Our policy file looks as shown below. This policy successfully downloads and activates "/main_bundle/authz.tar.gz".

```
package discovery

bundle_config := {
  "bundles": {
    "main": {
      "service": "s3_service",
      "resource": bundle_name
    },
  },
  "default_decision": "/authz/allow",
  "default_authorization_decision": "/authz/allow"
}

bundle_name := "/main_bundle/authz.tar.gz"
```

The issue happens when we try to download a certain version of this main_bundle. i.e the below policy gives us 403 error on S3.
```
package discovery

bundle_config := {
  "bundles": {
    "main": {
      "service": "s3_service",
      "resource": bundle_name
    },
  },
  "default_decision": "/authz/allow",
  "default_authorization_decision": "/authz/allow"
}

bundle_name := "/main_bundle/authz.tar.gz?versionId=XYZ" //where XYZ is the versionId
```

From the S3 perspective, the error is being thrown specifically from a 'SignatureDoesNotMatch' error due to the requester information. Instead of the IAM ID and session being passed, S3 is not receiving either of these values resulting in the signature mismatch when S3 tries to verify the signature.

I can see the correct url being created and sent to S3. We suspect the issue is happening because of the url parameters given after the "?",  in this case versionId which is resulting in sigv4 mismatch. 

One possible solution could be to add some extra parameters for bundle configuration or update OPA's aws authentication plugin to exclude anything after "?" in URL.

## Expected behavior

OPA Should be able to download S3 versioned objects from the past by specifying version Id in the bundle_name as shown in above example.

## Additional context

Boot Config is shown below (actual 

services:
  s3_service:
    url: ${S3_BASE_PATH} //hard data hidden for obvious reasons
    response_header_timeout_seconds: 5
    credentials:
      s3_signing:
        metadata_credentials:
          aws_region: ${AWS_DEFAULT_REGION}

discovery:
  resource: /discovery/discovery.tar.gz
  decision: discovery/bundle_config
  polling:
    min_delay_seconds: 10
    max_delay_seconds: 20

### PR DESCRIPTION
**Pull request by sinhaaks**
Add query param in canonical request of aws Sigv4 signature to avoid 403 from aws

Fixes #4954

Signed-off-by: Ankit Kumar Sinha <ankitsinhaiitg@gmail.com>

### CODE REVIEW

**Review by senaas1995 — APPROVED** [review]

**Comment by philipaconrad** [comment]
@sinhaaks Please do **not** close and recreate this issue again, as you did earlier in #4976 , #4975 , #4974 , and #4973 . Your contribution is appreciated, but there's an easier way to update your Pull Requests! (See below)

You can update your PR if it's behind the `main` branch by doing the following:
```
git checkout main
git pull
git checkout ankits-4954
git rebase
```
Assuming there are no merge conflicts, you can then force-push to the `ankits-4954` branch, and this PR will auto-update.
```
git push -f ankits-4954
```
You *will* get a warning message on the command line, which you can safely ignore. This is normal when force-pushing to a remote with Git. Assuming you rebased correctly, you'll have nothing to worry about.

**Comment by philipaconrad** [comment]
@sinhaaks Do you have a test case or test procedure for this change, so that I another maintainer can try it out? :smile:

**Comment by sinhaaks** [comment]
> @sinhaaks Please do **not** close and recreate this issue again, as you did earlier in #4976 , #4975 , #4974 , and #4973 . Your contribution is appreciated, but there's an easier way to update your Pull Requests! (See below)
> 
> You can update your PR if it's behind the `main` branch by doing the following:
> 
> ```
> git checkout main
> git pull
> git checkout ankits-4954
> git rebase
> ```
> 
> Assuming there are no merge conflicts, you can then force-push to the `ankits-4954` branch, and this PR will auto-update.
> 
> ```
> git push -f ankits-4954
> ```
> 
> You _will_ get a warning message on the command line, which you can safely ignore. This is normal when force-pushing to a remote with Git. Assuming you rebased correctly, you'll have nothing to worry about.

Thank You I'll follow this now.

**Review by anderseknert — COMMENTED** [review]
Since no tests are provided here — has this been tested manually against AWS resources **with** the query string component?

I take it that if there is no query component `req.URL.RawQuery` will just be empty and therefore behave as previously.. but we should at minimum confirm that this actually works 😅

**Comment by sinhaaks** [comment]
> @sinhaaks Do you have a test case or test procedure for this change, so that I another maintainer can try it out? 😄

I followed this repo to recreate the issue and tested after change that things are working - https://github.com/LuckySpb/opa-s3-sigv4 
I created a private s3 bucket in my AWS account to test

**Comment by sinhaaks** [comment]
> Since no tests are provided here — has this been tested manually against AWS resources **with** the query string component?
> 
> I take it that if there is no query component `req.URL.RawQuery` will just be empty and therefore behave as previously.. but we should at minimum confirm that this actually works 😅

I created a private S3 bucket with objects having multiple versions and that worked fine after adding RawQuery. I used commands in this repo https://github.com/LuckySpb/opa-s3-sigv4

**Comment by anderseknert** [comment]
Thanks @sinhaaks, much appreciated!

@senaas1995 @LuckySpb could you please verify that this solves your issue? You should be able to do so using the OPA built with this PR: https://github.com/open-policy-agent/opa/actions/runs/2810338838

(see the Artifacts section to the right)

**Comment by LuckySpb** [comment]
I have confirmed that solution works fine
Logs are showing that versioned s3 object can be downloaded successfully

`{"headers":{"Accept-Ranges":["bytes"],"Content-Length":["337"],"Content-Type":["application/x-gzip"],"Date":["Mon, 08 Aug 2022 21:23:02 GMT"],","X-Amz-Request-Id":["53W5XZDQPHM7MD9C"],"X-Amz-Version-Id":["M1JY81qsF_EPX_u2nJcsruFhl9XyB6NK"]},"level":"debug","method":"GET","msg":"Received response.","status":"200 OK","time":"2022-08-08T17:23:00-04:00","url":"https://opa-s3-test2-auth.s3.amazonaws.com/authz.tar.gz?versionId=M1JY81qsF_EPX_u2nJcsruFhl9XyB6NK"}
`

[log-with-fix.txt](https://github.com/open-policy-agent/opa/files/9285134/log-with-fix.txt)

**Review by LuckySpb — APPROVED** [review]

**Review by anderseknert — APPROVED** [review]

**Comment by philipaconrad** [comment]
Thanks for handling the review/merge, @anderseknert !

**Comment by LuckySpb** [comment]
@anderseknert @philipaconrad what's the release cycle for the agent?
When we can try to test released version?

**Comment by anderseknert** [comment]
Monthly, so roughly 20 days from now until the next release.

**Pull request merged**
