### PR TITLE
Allow print calls in IR

### PR DESCRIPTION
**Pull request by anderseknert**
Since this was unset on the compiler for -t plan, print calls got erased from the plans. Since this is useful for debugging plan execution, we should allow print in this context. If undesired, this can still be disabled via the capabilities feature.

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

**Comment by srenatus** [comment]
> If undesired, this can still be disabled via the capabilities feature.

Would removing the capability cause compile errors or erase the print calls?

**Comment by anderseknert** [comment]
@srenatus cause compile errors, I would assume. But I can test it tonight to verify. That's what you'd expect, right?

**Comment by srenatus** [comment]
Yes, sorry. Just pointed out that while there is a way to disable print with this PR, it's not quite the same as before.

But from the plan usage that I'm aware of, it's probably ok to change the default here.

**Comment by anderseknert** [comment]
The obvious other way to disable print is of course in the IR implementation :)

Also confirmed:
```
❯ opa build -t plan --capabilities capabilities.json policy.rego
error: 1 error occurred: policy.rego:6: rego_type_error: undefined function internal.print
```

**Review by srenatus — APPROVED** [review]
Thanks! Let's get this merged.

**Pull request merged**
