### PR TITLE
[docs/website] Link to OPA Ecosystem from docs

### PR DESCRIPTION
**Pull request by charlieegan3**
This PR makes the following changes to the website Ecosystem content and linking:

* Creates and assigns categories to various projects where information is available.
* Displays top level categories on Ecosystem page
* Links to categories from various relevant locations within the docs.
* Embeds related Ecosystem projects at the ends of some docs pages where there are fewer than 6 and all have related content to the page in question.
* Implements Hugo partials and shortcodes to make this extensible in future.
* Updates to ecosystem projects to keep them current
* Adds various, previously unlisted, OPA ecosystem projects

### CODE REVIEW

**Comment by srenatus** [comment]
I wasn't able to find out by myself -- what determines the use of "by VENDOR" vs plain "VENDOR" here? 👇 

image

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/pull/6064/files#diff-d7824d254a89d3d00b2f4b30619017056bb7c90bb335a493d4dae59eb38ecbe7R16-R24 found it. Nevermind ✔️

**Review by srenatus — APPROVED** [review]
Impressive Hugo skills here. And the outcome looks great. Thanks a lot. 👏

**Review by philipaconrad — DISMISSED** [review]
As @srenatus noted, there's a substantial amount of Hugo partials-wrangling going on here. Well done-- the results looks great! :smile:

**Comment by srenatus** [comment]
It looks a bit too wide on my mobile, but that shouldn't block merging this great improvement. Also, I'm too daft to create a screenshot right now 😅

**Comment by charlieegan3** [comment]
> It looks a bit too wide on my mobile

👍 Ahh, I think I can fix that.

**Review by ashutosh-narkar — DISMISSED** [review]

**Comment by charlieegan3** [comment]
0035ca9d629fa5e607224a29f4b1d26ab4bdc0d6 adds a few more ecosystem project sections.

**Comment by srenatus** [comment]
Mobile looks good now, thanks!

**Pull request merged**
