### PR TITLE
add compiler.Compiler and compiler.optimizer WithEnablePrintStatement…

### PR DESCRIPTION
**Pull request by kevinstyra**
…s option and pass through to ast.Compiler

When using the compiler.Compiler; rego "print" statements get removed and there is no way on the API to enable them.
So the PrintHook is broken.

Signed-off-by: Kevin St. Pierre <kevin@styra.com>

### CODE REVIEW

**Comment by srenatus** [comment]
I'm afraid that code path is underrepresented in our tests... So I feel bad about asking you to add coverage, but perhaps you could include an example log of what kind of thing happened before and what happens now? 🤔

**Comment by anderseknert** [comment]
Could we please have a line or two added to the description stating what problem this solves? 😊

**Comment by kevinstyra** [comment]
updated description and added unit test.

**Review by tsandall — APPROVED** [review]
LGTM

**Pull request merged**
