### PR TITLE
Add Trino to OPA ecosystem

### PR DESCRIPTION
**Pull request by mosabua**
### Why the changes in this PR are needed?

The OPA website does not yet include a mention of the Trino support. 

### What are the changes in this PR?

This PR adds information about Trino and the Trino OPA integration to the OPA website.

### Further comments:

Please ping me via comments or on Trino or OPA slack if I need to do anything else to get this PR merged.

### CODE REVIEW

**Comment by mosabua** [comment]
Note that I cant seem to build the website locally but the error message seem unrelated to my changes. Is the main branch currently busted?

**Comment by mosabua** [comment]
Maybe my Hugo version is too new (installed with brew) but wouldnt the build here at least work?

**Comment by mosabua** [comment]
Installed right version of Hugo now .. getting further but site build is still failing.

**Comment by ashutosh-narkar** [comment]
@mosabua thanks for submitting this. The failure is unrelated to your changes.  

It looks like Netlify is unable to install Go v1.22 and falls back to Go v1.19. Now the minimum version needed to build OPA is Go v1.20 so the build fails. We're looking into this.

**Comment by mosabua** [comment]
Sounds good @ashutosh-narkar .. just let me know when I can rebase or whatever to get this ready for merge and publish

**Comment by ashutosh-narkar** [comment]
> Sounds good @ashutosh-narkar .. just let me know when I can rebase or whatever to get this ready for merge and publish

@mosabua please rebase the PR. Thanks!

**Comment by mosabua** [comment]
Rebase done @ashutosh-narkar

**Comment by mosabua** [comment]
Deploy preview looks good. Let me know if any other changes are needed for a merge

**Review by ashutosh-narkar — APPROVED** [review]
LGTM. Thanks @mosabua!

**Pull request merged**
