### PR TITLE
internal/wasm/sdk: Use wasmtime.

### PR DESCRIPTION
**Pull request by koponen-styra**
This uses the wasmtime 0.21 C library with an additional go packaging patches already upstreamed for the future 0.22.

Signed-off-by: Teemu Koponen <koponen@styra.com>

### CODE REVIEW

**Comment by srenatus** [comment]
💭Interesting! If we go with this, we could revisit https://github.com/open-policy-agent/opa/pull/2874 and make the build flag `opa_wasm`, to not include the specifc lib used.

**Comment by koponen-styra** [comment]
> 💭Interesting! If we go with this, we could revisit #2874 and make the build flag `opa_wasm`, to not include the specifc lib used.

**Comment by syrusakbary** [comment]
Note: we are about to upgrade Wasmer and Wasmer-go to 1.0 with significant speed improvements (2x faster compared to wasmtime when using the LLVM backend).

The new API of Wasmer-go is also feature complete and [easy to use](https://github.com/wasmerio/wasmer-go/tree/master/examples)!

We had some memory leaks in the latest Wasmer-go, but all shall be solved within the next 2 days! :)

**Comment by koponen-styra** [comment]
> 💭Interesting! If we go with this, we could revisit #2874 and make the build flag `opa_wasm`, to not include the specifc lib used.

Done.

**Comment by koponen-styra** [comment]
> > Note: we are about to upgrade Wasmer and Wasmer-go to 1.0 with significant speed improvements (2x faster compared to wasmtime when using the LLVM backend). The new API of Wasmer-go is also feature complete and [easy to use](https://github.com/wasmerio/wasmer-go/tree/master/examples)!
> 
> We had some memory leaks in the latest Wasmer-go, but all shall be solved within the next few days... I'd love to know if there are other reasons that pushed you away from using Wasmer! (so we can fix them!)

Memory issues were/are the most pressing issue.

**Comment by tsandall** [comment]
I'm going to pickup where this left off using wasmtime-go v0.22.0

**Pull request closed without merging**
