### PR TITLE
cli: try fix issues reported in 'oracle' command

### PR DESCRIPTION
**Pull request by anderseknert**
Try and fix errors issues reported here:
https://github.com/open-policy-agent/vscode-opa/issues/81

1. Only include .rego files in definition location checks
2. Don't hang if input not provided on stdin

### CODE REVIEW

**Review by ashutosh-narkar — COMMENTED** [review]
Changes look good. Can we please add a test case for this?

**Comment by anderseknert** [comment]
@ashutosh-narkar honestly not sure how to test "commands does not hang if no data provided on stdin". Any recommendation? I've tested it manually, both from the command line and through VS Code.

**Comment by ashutosh-narkar** [comment]
> @ashutosh-narkar honestly not sure how to test "commands does not hang if no data provided on stdin". Any recommendation? I've tested it manually, both from the command line and through VS Code.

I was just suggesting a simple unit test [here](https://github.com/open-policy-agent/opa/blob/main/cmd/oracle_test.go#L16) which would test only _rego_ files are loaded but maybe that is testing the loader more.

**Review by ashutosh-narkar — DISMISSED** [review]

**Comment by anderseknert** [comment]
Ah, yes, that part might be easier to test. I'll give it a shot.

**Comment by anderseknert** [comment]
@ashutosh-narkar I’ve added two non-Rego files to the test, but I’m not sure how to test that they got excluded by then filter. Maybe the result is good enough?

**Comment by ashutosh-narkar** [comment]
> @ashutosh-narkar I’ve added two non-Rego files to the test, but I’m not sure how to test that they got excluded by then filter. Maybe the result is good enough?

Yes that's good. Thanks!

**Review by ashutosh-narkar — APPROVED** [review]

**Pull request merged**
