### PR TITLE
ccbr tool join in opa ecosystem

### PR DESCRIPTION
**Pull request by niuzhi**
ccbr tool join in opa ecosystem
update code file:docs/website/data/integerations.yaml

history discussion:
https://github.com/open-policy-agent/opa/pull/5088

### CODE REVIEW

**Comment by niuzhi** [comment]
DCO failed

**Comment by anderseknert** [comment]
Good morning @niuzhi! There's no need to re-opening PRs only because of some errors reported in the pipeline. Let's fix them instead. In order to pass the DCO check, you'll need to sign your commit:
```
git commit --amend --signoff
git push --force
```
You should also make sure to squash your commits into a single one:
```
git rebase --interactive <commit hash of commit before your changes>
```
You can read more about that process in various tutorials online.

**Comment by niuzhi** [comment]
@anderseknert  hello anderseknert 
Thank you very much for your reply, but because my current environment cannot use git to operate github due to network problems, I completed it through github destop. Regarding the problem of DCO, can you help fix it, thank you very much!

**Comment by anderseknert** [comment]
@niuzhi I can't add a signoff to somebody else's commits... but if you can alter the commit message via GitHub desktop, you can just put the signoff on the last line, i.e:

```
Signed-off-by: Your Name <your@email.com>
```

**Comment by niuzhi** [comment]
@anderseknert  Thank you very much for your reply, I will try it

**Pull request closed without merging**
