### PR TITLE
ccbr tool join in opa ecosystem

### PR DESCRIPTION
**Pull request by niuzhi**
ccbr tool join in opa ecosystem
update code file:docs/website/data/integerations.yaml

history discussion:
https://github.com/open-policy-agent/opa/pull/5088

Signed-off-by: Zhi Niu yulinniuzhi@163.com

### CODE REVIEW

**Comment by charlieegan3** [comment]
Hey, I think we're having the same issue we were having here: https://github.com/open-policy-agent/opa/pull/5573#issuecomment-1396713122.

We're happy with the content of the PR, I can correct the commit message at merge time. Would you like to me to do that for you?

**Comment by charlieegan3** [comment]
Hey @niuzhi, I don't think reverting the commit dc469b42cab9c4cb479a14e3e7e490c927e6baff will help here since the old commit is still there.

Would you like me to help?

**Comment by niuzhi** [comment]
@charlieegan3 
Thank you very much, it will be my pleasure if you can help me. Looking forward to your news of correct integration

**Comment by charlieegan3** [comment]
Great! 🙂

First, what we can do is wait for all the checks to finish.

The DCO one will still be failing, however I can update the commit message when I merge it in.

So for now, we wait! 🕐

**Comment by charlieegan3** [comment]
All the checks have passed - other than the DCO check.

However, you have signed it off with your email. I'm going to merge now and correct the commit message. 📝

**Pull request merged**
