### PR TITLE
build: updates for go 1.17

### PR DESCRIPTION
**Pull request by srenatus**
- [ ] `go 1.16` in `go.mod`
- [x] `1.17` in `.go-version`
- [ ] using the go:embed directive instead of our handcrafted binary embedding code
- [x] updated x509 errors (#3547)
- [x] updated tls_test.go flag handling

----
☝️ The remaining TODOs can be tackled when we decide that it's time to give up support for 1.15.

### CODE REVIEW

**Comment by tsandall** [comment]
Is there anything that library users need to be aware of?

**Comment by srenatus** [comment]
> Is there anything that library users need to be aware of?

The Go module will no longer be usable from the (now unsupported) golang version 1.15.x:

```
internal/compiler/wasm/opa/opa.go:8:8: cannot find package "." in:
        /src/vendor/embed
bundle/filefs.go:6:2: cannot find package "." in:
        /src/vendor/io/fs
```

**Comment by tsandall** [comment]
Are you at all worried about existing users that haven't updated beyond Go 1.15 yet? I realize it's unsupported but it's only a year old. Do we see any speedup from updating to Go 1.17? It would be nice to at least have some performance improvements if we're breaking people 😅

**Comment by srenatus** [comment]
Honestly, I'm torn. It would be nice not to worry about old versions, and I think golang had been so easy to update it past (its stability promise kept), I wonder how relevant the 1.15 compat really is... But we can do this in a compatible way, for now, for sure. (Ship builds built with 1.17, keep OPA compilable with 1.15)

**Comment by srenatus** [comment]
Dialled it back a little, and added a CI test to ensure we can build with several different golang versions (1.15 and 1.16).

**Review by tsandall — APPROVED** [review]

**Pull request merged**
