### PR TITLE
Fixed home page learn more buttons

### LINKED ISSUE #2205: docs: Homepage links to "Learn More" should be more visually distinct
On the home page for OPA https://www.openpolicyagent.org/ we have:

image

Which is somewhat confusing as it looks like one big button but each of the text items is a separate link. We should split them up into separate buttons or something more distinctive.

### PR DESCRIPTION
**Pull request by arunbsar**
Fixed home page learn more buttons
[demo](https://opa-6816e6.netlify.app/)

Fixes #2205

Signed-off-by: Arun Kumar <arunbsar@gmail.com>

### CODE REVIEW

**Comment by patrick-east** [comment]
Thanks @arunbsar this is looking pretty good. I think its is definitely an improvement, and the new buttons look nice.

Couple of things we'll need to address:
image
* If we can align the "Learn More" text and the buttons that would be great, and maybe make it a little bit more bold font.
* We should try and center the whole thing in the page, it looks like its kind of left justified right now
image
In a more narrow mobile view they wrap (which is really cool) but we probably want a little bit of spacing between the rows. Might just require some like padding/margin on top of them or something.

**Comment by peterstyra** [comment]
Hi Arun, I'm Peter Shepherd, the new UX guy at Styra - Great work, thanks so much! 
Here are some small recommendations:
- As Patrick said, please Center the Learn more blocks on the page
- For the "Learn More" title
  - Change "Learn more:" to "Learn More"
  - Use the same font style/size as the secondary header style: 
     - See "Context-aware, Expressive..." under Declarative Policy
- Buttons
  - Use same rounded style as Open in Playground button
  - Perhaps make them all the same width

**Comment by arunbsar** [comment]
Hi Peter, have updated the code as per your comments, check it and let me know if any changes required 

[Demo](https://opa-6816e6.netlify.app/)

**Comment by peterstyra** [comment]
Awesome Arun, nice build on the Learn More style treatment: it's well
matched within the sections -  ship it!

Thanks and have a great weekend,
- Peter

**Pull request merged**
