### PR TITLE
Add note about updating search index after release

### PR DESCRIPTION
**Pull request by charlieegan3**
https://github.com/open-policy-agent/opa/issues/6133#issuecomment-1666152457

### CODE REVIEW

**Review by anderseknert — DISMISSED** [review]
LGTM! 

"This should only be necessary if there are new pages or changes to titles."

Is that not always the case when a new release is out? I.e. the new v0.xx.x will need to have new pages, no?

The pages I saw missing in the index were not modified by the last release, or not that I'm aware of.

**Comment by charlieegan3** [comment]
Interesting, I'd have thought that you'd be searching the `latest` version which should still be there until the index is updated by the crawler.

Screenshot 2023-08-08 at 15 27 38

**Comment by charlieegan3** [comment]
I've updated the comment to make it less optional, and set the crawler to run daily at the same time to make it less likely to be broken for a long time if someone forgets.

**Review by ashutosh-narkar — APPROVED** [review]
Thanks @charlieegan3!

**Pull request merged**
