### PR TITLE
Minor corrections

### PR DESCRIPTION
**Pull request by princerachit**

### CODE REVIEW

**Comment by princerachit** [comment]
Will fix the DCO

**Comment by tsandall** [comment]
Thanks @princerachit! Once the DCO is signed we can merge this.

**Comment by tsandall** [comment]
hey @princerachit as soon as you sign the DCO, we can merge this! Thanks again for submitting the patch.

**Comment by tsandall** [comment]
hey @princerachit just a reminder that if you sign the DCO we can merge this. If we don't hear back in a couple days we can submit a separate PR for this.

**Comment by princerachit** [comment]
@tsandall sorry for the delay. I have signed off

**Comment by tsandall** [comment]
thanks @princerachit !

**Pull request merged**
