### PR TITLE
Adding Digraph to ADOPTERS.md

### PR DESCRIPTION
**Pull request by jamesphlewis**
Digraph is using OPA to power its rules engine to test IAC for compliance

### CODE REVIEW

**Comment by anderseknert** [comment]
Thanks! In order to have this merged, you'll need to add a signoff to your commit. You can do this with:

```
git commit --amend --signoff
git push --force
```

**Comment by jamesphlewis** [comment]
@anderseknert done! Let me know if there's anything else you need!

**Comment by anderseknert** [comment]
@jamesphlewis a mention of OPA on your website and a link back to the project would be neat ;) But it's not a requirement, and it looks like you're in an early stage still, so maybe you'll add it later.

**Comment by jamesphlewis** [comment]
@anderseknert - thanks for the quick response! We are happy to link to the project, we are in the middle of building our website so once that's ready we will add a link!

**Pull request merged**
