### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ken5scal**
#869

### CODE REVIEW

**Comment by tsandall** [comment]
@ken5scal LGTM. You will need to sign off on your changes before we can merge. See https://github.com/probot/dco#how-it-works for details.

**Comment by ken5scal** [comment]
@tsandall thanks, I signed it off

**Comment by tsandall** [comment]
@ken5scal it looks like you have some conflicts. Once you resolve those and update the PR, we can merge.

**Comment by ken5scal** [comment]
seems green now!

image

**Comment by tsandall** [comment]
@ken5scal it looks like you ran into trouble merging changes from upstream into your fork. You can see that the PR includes 6 commits -- 4 of which are from other people.

What I recommend you do is cherry-pick your commit into a new branch and re-open the PR. 

For example:

```
git checkout master # this assumes you have a clean master branch
git fetch upstream
git rebase upstream/master # now your master should be synched with upstream/master

git checkout -b fix-typo-new
git cherry-pick 25e85ac7bc9c113d48dd1d0ae970ff5c884c724e
```

Then you can push the new branch (fix-typo-new) and open a PR from that.

The DEVELOPMENT.md file has a description of how you can sync changes from upstream and submit PRs to OPA: https://github.com/open-policy-agent/opa/blob/master/docs/devel/DEVELOPMENT.md#workflow (note, this isn't specific to OPA, many projects work with Git like this.)

We try to keep the commit log as clean as possible because it's invaluable when looking back and trying to understand why changes were made. There are guidelines on the commit messages in the CONTRIBUTING.md file here: https://github.com/open-policy-agent/opa/blob/master/CONTRIBUTING.md#code-contributions

**Comment by ken5scal** [comment]
Thanks, let me try it out.

**Pull request closed without merging**
