### PR TITLE
Fixed various typos on user-facing tutorials

### PR DESCRIPTION
**Pull request by plallin**
This PR fixes a few typos found while taking this tutorial: https://www.openpolicyagent.org/docs/kubernetes-admission-control.html

While those typos are trivial, the tutorial is user-facing and therefore I believe it would benefit from being typos-free.

### CODE REVIEW

**Comment by tsandall** [comment]
@plallin thanks for submitting these fixes! It looks like your branch has conflicts and merge commits. You might want to re-open the PR with a fresh commit to resolve this (or you can rebase locally but that's a bit more work.)

**Comment by plallin** [comment]
@tsandall thanks for your prompt reply 🙂 I think the conflicts are fixed now, can you check again? If there's still issues I'll fix them in a few hours

**Comment by tsandall** [comment]
I still see them...

screenshot from 2019-02-04 11-06-18

It might be simpler to just close this PR. Apply the diff to a clean branch and then resubmit.

**Comment by plallin** [comment]
@tsandall ah, that's unfortunate, I don't get that same view on my end. I'll resubmit in a few hours

**Pull request closed without merging**
