### PR TITLE
opa test: add traces on errors

### PR DESCRIPTION
**Pull request by srenatus**
This should be following the outline of https://github.com/open-policy-agent/opa/issues/856#issuecomment-408908578 closely.

I tend to agree that #961 would be quite cool, but I guess this is one step into the right direction, at least? 😃

### CODE REVIEW

**Comment by srenatus** [comment]
> I think it would be better if each trace was reported separately. 

💯 just need to figure out how to do do that 😄 

> In terms of implementation, perhaps Result could be extended to include an optional trace field.

👍 that would also make the JSON output better

**Comment by srenatus** [comment]
OK, so it's per-test now; and part of `Result`, so it'll also look a bit nicer (and be more useful) in JSON.

What's missing is trace indentation. Ran out of time for that one.

I will of course squash these before we merge anything, but I'll keep history intact until then 😃

**Comment by tsandall** [comment]
Awesome! A couple notes (neither are blocking.)

1. I think it would be better if the trace field was of type `[]*topdown.Event` instead of `string`. This will enable programs to consume the test output more readily. The pretty printer can still turn the buffer into a human readable trace.

2. I think the test runner interface should be extended (or just broken, since I don't think it's widely used.) Instead of passing the tracer into the runner and then having the runner cast and reset the tracer, the runner could accept a tracer factory and instantiate a new tracer on each run. One alternative would be to extend the tracer interface to include a "reset" operation but I would lead towards the factory approach in the spirit of keeping the tracer interface as simple as possible.

Feel free to fix the struct tag issue and squash your changes, I can merge the PR as-is and make those adjustments (and do the indenting while I'm at it.)

🎆

**Comment by srenatus** [comment]
> Feel free to fix the struct tag issue and squash your changes, I can merge the PR as-is and make those adjustments (and do the indenting while I'm at it.)

@tsandall sounds great -- all squashed. Thank you! 🎉

**Pull request merged**
