### PR TITLE
Parse PEM or DER data in crypto built-ins

### LINKED ISSUE #2557: PEM decoding in crypto certificate built-ins
I'm interested in parsing  x509 pem encoded encoded certificates in my rules (sourced from k8s secrets) but found that this didn't seem to be possible with the current crypto built-ins.

While the CSR built-in parses data in the [pem format](https://github.com/open-policy-agent/opa/blob/master/topdown/crypto.go#L75-L78), the certificate function [does not](https://github.com/open-policy-agent/opa/blob/master/topdown/crypto.go#L23-L33).

This was raised in the [PR for the CSR built-in](https://github.com/open-policy-agent/opa/pull/2444#discussion_r432665898).

I'm in the position where I'd like to decode x509 pem encoded certificates/chains (as are found in k8s secrets) and am wondering what the best approach would be to support this in OPA. Perhaps a new built-in to do pem decoding and output as base64, ready for input to `crypto.x509.parse_certificates` would be the least breaking? But then the inconsistency with cert/csr handling remains. Would be interested to hear any ideas.

### PR DESCRIPTION
**Pull request by charlieegan3**
Fixes #2557

In #2557 I highlighted an inconsistency in our parsing of x509 data
where CSRs were PEM decoded and certificate chains where DER data.

This change allows both built-ins to accept data as DER or PEM wrapped
in base64.

While addressing the inconsistency, this also makes it possible to
decode a PEM certificate chain - the use case that prompted me to make
this change.

I have also updated the tests to use common names as the expected
output. I feel that this makes it clearer what we're dealing with
without detracting from the utility of the test cases (since we're not
really testing crypto/x509 from the standard library).

### CODE REVIEW

**Comment by tsandall** [comment]
@patrick-east can you take a look at this? One thing I noticed is that we're not supporting the PEM wrapper. I thought that was one of the motivations here.

**Comment by charlieegan3** [comment]
The PEM wrapper should be supported, but it needs to be input as base64. I followed what the CSR function was already doing to avoid handling three cases:
- pem in b64 :heavy_check_mark: 
- pem as string :x: 
- der as b64 :heavy_check_mark:

**Comment by tsandall** [comment]
I think we should make both support the PEM string format. We can do this by checking if the input string starts with `---` and then decide whether to base64 decode or not.

**Comment by charlieegan3** [comment]
Ok sure. I can have a go at that later. I'll look to support all three of those forms of input for both chains and CSRs.

**Comment by charlieegan3** [comment]
I have made the change to support PEM string input in c50dd2044473f3614f143b0b04fd47240263596d

**Comment by charlieegan3** [comment]
:blush: thanks both!

**Pull request merged**
