### PR TITLE
bundle/test: add handle function's result

### PR DESCRIPTION
**Pull request by cyclinder**
https://github.com/open-policy-agent/opa/blob/main/bundle/bundle_test.go#L31 the result of function Equal not used,
This pr increases the processing of function results.

Fixes:[issue3850](https://github.com/open-policy-agent/opa/issues/3850)

### CODE REVIEW

**Comment by srenatus** [comment]
We could but it's s bug in the implementation... I'm not sure about the best way forward yet, we'll get back to you. If you'd like to get this done quickly, please change the PR so that it skips the test.

**Comment by cyclinder** [comment]
> 💡 AddRoots does what it's supposed to do if the Manifest it's called on doesn't need the`Init()` because it's already been initialized. In real world usage, that'll be `opa build` invoked with a manifest file. For this test, we should be good to go if we replace
> 
> ```go
> var m Manifest
> ```
> 
> by
> 
> ```go
> m := Manifest{Roots: &[]string{}}
> ```
> 
> @cyclinder If you'd still be interested in pursuing this, please just re-open the PR. 😃

thank your nice job, iI'm sorry I just saw it now.

i'm so love to do this, can I re-open this pr ?

**Comment by srenatus** [comment]
Yes that would be great. Thank you

**Comment by cyclinder** [comment]
@srenatus thank you so much

**Review by srenatus — APPROVED** [review]
🎉 Thanks for bearing with me here. The commit looks good, I'll get this merged once it goes green.  👏

**Pull request merged**
