### PR TITLE
make func newDescriptor public

### PR DESCRIPTION
**Pull request by antgubarev**
I compile bundle from key-value storage. But I can't implement DirectoryLoader for that beacause newDescriptor is private. I would like to use bundle.CustomReader. Is it possible? 
Thanks!

### CODE REVIEW

**Review by anderseknert — COMMENTED** [review]
Hi @antgubarev 👋 And thanks for submitting this. Can you help me understand why you need `newDescriptor` to be public for your custom implementation of a directory loader? The `Descriptor` struct is public already, so could you not just use that directly?

**Comment by anderseknert** [comment]
Ah, right — I didn't think of checking the fields. I don't mind making the constructor public, not sure if anyone else has objections. 

The DCO requirement needs to be fixed though. Just sign the commit like:

```
git commit --amend --signoff
git push --force
```

**Comment by ashutosh-narkar** [comment]
Seems reasonable. We should probably make [withCloser](https://sourcegraph.com/github.com/open-policy-agent/opa@f063c90275bed61c4381db771162724e191f2d3c/-/blob/bundle/file.go?L74) public too.

**Comment by srenatus** [comment]
> Seems reasonable. We should probably make [withCloser](https://sourcegraph.com/github.com/open-policy-agent/opa@f063c90275bed61c4381db771162724e191f2d3c/-/blob/bundle/file.go?L74) public too.

Hmm we could also check if we've got an io.Reader that also an io.Closer and call its Close() opportunistically in `(*Descriptor).Close()`. Then we wouldn't need the withCloser anymore.

**Comment by antgubarev** [comment]
@anderseknert I fixed commit and made WithCloser public too

**Review by anderseknert — APPROVED** [review]

**Comment by ashutosh-narkar** [comment]
@antgubarev can you please squash your commits and fix the [sign-off ](https://github.com/open-policy-agent/opa/pull/6517/checks?check_run_id=20355869368)? We can then get this in.

**Comment by antgubarev** [comment]
@ashutosh-narkar Sorry) Done.

**Review by ashutosh-narkar — APPROVED** [review]

**Comment by ashutosh-narkar** [comment]
@antgubarev can you please fix the DCO again. Not sure what's happening.

**Comment by antgubarev** [comment]
> @antgubarev can you please fix the DCO again. Not sure what's happening.

@ashutosh-narkar  Fixed.

**Pull request merged**
