### PR TITLE
Document different between = and := in rules

### LINKED ISSUE #1218: Document different between = and := in rules
# Expected Behavior

A documentation section clearly explaining the difference

# Actual Behavior

No proper documentation

# Steps to Reproduce the Problem

  1.
  2.
  3.

# Additional Info

### PR DESCRIPTION
**Pull request by repenno**
Fixes #1218

Signed-off-by: repenno <rapenno@gmail.com>

### CODE REVIEW

**Comment by tsandall** [comment]
Thanks for folding what @timothyhinrichs said in Slack into the docs. We already have a section that describes the difference between `=` and `:=` here: https://www.openpolicyagent.org/docs/how-do-i-write-policies.html#operators

That said, we have an open task to go through the docs and replace usage of `=` with `:=` and `==` wherever possible: https://github.com/open-policy-agent/opa/issues/952

As such, I think we can just close this PR and the related issue.

**Comment by repenno** [comment]
I think the current document explanation is very dry does not provide enough context such as the one in slack.

**Comment by tsandall** [comment]
Tim certainly has a way of making logic lively. @repenno if you'd like to factor his answer into the existing section, that would be great.

**Comment by repenno** [comment]
Done, patched current documentation

**Pull request closed without merging**
