### PR TITLE
topdown: Added a new array reverse function

### LINKED ISSUE #3736: Add a built-in function to reverse arrays and strings
OPA does not currently include a built-in function for reversing strings and arrays. While it's possible to write a comprehension that does this, it's a bit cumbersome. We can add two simple built-in functions for reversing strings and arrays:

```
strings.reverse(str) => str
array.reverse(arr) => arr
```

### PR DESCRIPTION
**Pull request by olamiko**
ast: Updated the builtins list

partially fixes #3736

Signed-off-by: Olamide Omolola <omololaolamidex@gmail.com>

### CODE REVIEW

**Comment by anderseknert** [comment]
Lint failures, and needs unit tests, but looks like a good start!

**Comment by srenatus** [comment]
Heya. Are you still working on this? 😃

**Comment by olamiko** [comment]
Hi @srenatus, yes, I already wrote the functions for reversing. Next step is to test them and then update the website

**Comment by srenatus** [comment]
@olamiko I've converted this to a draft. Please check "Ready for review" when you get to pick this up 🚀

**Comment by tsandall** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
