### PR TITLE
Add a few missing tests

### PR DESCRIPTION
**Pull request by anderseknert**
Hacking on IR implementations for the builtins revealed
some missing tests, which are added here.

Also brought back the comment providing instructions for
running the tests in the helloworld directory, as this was
mistakenly removed by the massive cleanup PR some month back.

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

**Review by philipaconrad — APPROVED** [review]
These look great! :smiley: Assuming the flakey MacOS tests pass, this should be good for merge.

A slightly more descriptive commit message would be the only change I'd suggest, maybe something like: `testcases: Add missing metadata, x509, helloword tests`?

**Comment by anderseknert** [comment]
Thanks @philipaconrad 👍 I've added the names of the builtin functions now covered by tests to the commit message.

**Comment by srenatus** [comment]
🤔 Do the `rule.metadata.*` calls even appear in the IR? I thought the _compiler_ rewrites those.

**Comment by anderseknert** [comment]
@srenatus yes - the purpose of the tests is to assert that.

**Review by philipaconrad — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
