### PR TITLE
builtins: Enhance io.jwt.verify_* builtins to accept JWK as a cert parameter.

### PR DESCRIPTION
**Pull request by koponen-styra**
Signed-off-by: Teemu Koponen <koponen@styra.com>

### CODE REVIEW

**Comment by koponen-styra** [comment]
For consistency across the jwt functions, I'm leaning towards changing the cert parameter always to be a string.

**Comment by tsandall** [comment]
> For consistency across the existing jwt functions, I'm leaning towards changing the cert parameter always to be a string.

Would this mean passing a JSON serialized string containing the JWK object to the verify functions? How do people intend to use this in their policies? Are they constructing the JWK objects inside the policy or loading the JWK object out of input/data?

**Comment by repenno** [comment]
Putting OPA aside for a moment...JWKs are many times fetched over HTTP or
read from file at time of verification.

If you remember, the original JWS stuff I added had a JWK fetch function
but we agreed to remove it.

**Comment by koponen-styra** [comment]
> Would this mean passing a JSON serialized string containing the JWK object to the verify functions? How do people intend to use this in their policies? Are they constructing the JWK objects inside the policy or loading the JWK object out of input/data?

Right, the parameter string would be a serialized JWK (or JWK set). It seems the common case is what @repenno described: the keys come in as input/data from outside of the policy.

**Pull request merged**
