### PR TITLE
Add Codecov threshold of 1% for project

### PR DESCRIPTION
**Pull request by patrick-east**
This should help eliminate some noise being caused on the CI jobs
marking PR's as not passing tests.

Signed-off-by: Patrick East <east.patrick@gmail.com>

### CODE REVIEW

**Comment by tsandall** [comment]
What does a "threshold of 1%" mean in this case? Does it mean that test coverage of the patched code must be greater than one percent?

**Comment by patrick-east** [comment]
Its only for how far its allowed to drop before marking the check as failed, so any PR could lower the project's overall number by up to 1% (not the per-patch coverage, which IMO is more interesting anyway). Note that reviewers should still see the change posted, it just wont give the PR the red X.

**Comment by patrick-east** [comment]
Docs: https://docs.codecov.io/docs/commit-status#threshold

**Comment by patrick-east** [comment]
Not sure how granular it is either, we could maybe try like 0.05% or something (i've been seeing 0.02% changes on PR's over the last day being marked as failing... which is somewhat of a mystery on its own)

**Pull request merged**
