### PR TITLE
Add initial implementation of search bar

### PR DESCRIPTION
**Pull request by lucperkins**
Addresses issue #1504.

@tsandall @patrick-east @kenfdev Honestly, I'm slightly shocked at how easy this was.

The bad news is that it's 100% magic, so I don't think there's much we can do to improve the search results/experience. But for an out-of-the-box thing, I think it's pretty damned okay.

**WARNING**: if you select one of the search results, it will take you out of the deploy preview and onto the production site. So if you click on a search result and the search bar is suddenly missing, that's expected behavior.

### CODE REVIEW

**Comment by tsandall** [comment]
@lucperkins that's pretty slick. @patrick-east WDYT?

**Comment by patrick-east** [comment]
It looked good a few min ago, I guess now it is having some trouble with the versioning stuff? (I don't see any results on the last preview build). Not sure if you are still bug fixing it but the mobile view search bar didn't show the search results under it, the container div is maybe too small?

Im super impressed at how simple that is to integrate, and if we can figure out the versioning things I'll be on board. My biggest concern with using it was the different versions of docs and the dev preview.. I'm cool sacrificing search on dev builds/previews if we can get versioning and this super simple integration 😄

**Comment by lucperkins** [comment]
@patrick-east The versioning logic should be fixed now (there was an issue re: `latest`).

**Comment by patrick-east** [comment]
Hmm, we might have done a disservice to ourselves by making the site so flexible on anchors and the version in urls. I'm seeing duplicate results with just slightly different urls (probably because we reference them differently in different places). For example a search for `regex` gives the first 3 results as links to:

https://www.openpolicyagent.org/docs/v0.12.0/language-reference/#regex
https://www.openpolicyagent.org/docs/latest/language-reference#regex
https://www.openpolicyagent.org/docs/latest/language-reference/#regex

All of them are arguably correct, and afaik actually link to the exact same content with url rewriting magic underneath 😆 

On the algolia site can we do some configuration to help tailor this sort of thing? Or would we need to do more enforcement on our site content?

**Comment by lucperkins** [comment]
@patrick-east As far as I know we don't really have any config levers on the Algolia side. You basically submit a site URL and they send you a JavaScript snippet via email (at least at the moment...I think DocSearch is still pretty young). So this would need to be addressed on our side. I'm a little bit bummed that their scraper takes the URL into account. Preferably it would only look for the `canonical` URL metadata and use that. I'll do some digging.

**Comment by lucperkins** [comment]
@tsandall @patrick-east I did some experimenting with tweaking the CSS and JS, but I can't figure out how to get it to work on mobile. I'm gonna get in touch with their support, but it's not clear what kind of turnaround time I'll get there (esp with KubeCon coming up next week). Would you two be okay with pushing this as a v0.1 with the mobile bar removed and somewhat redundant indexing?

**Comment by lucperkins** [comment]
@patrick-east Unfortunately I tested it out and the same problem arises outside of the navbar context.

**Comment by patrick-east** [comment]
@lucperkins no worries, I guess we'll have to wait and hear what their support team says.

Before merging I'd like to make sure @tsandall and @ashutosh-narkar and others are cool with adding it as-is. I'm thinking with kubecon going on right now maybe we should wait on the off chance we break something on the docs, I'm guessing new traffic will be driven to the site as folks are doing talks about OPA and promoting the project.

**Comment by tsandall** [comment]
My guess is that redundant results will cause a bit of confusion (and possibly frustration.) Users will click through but in the back of their minds they'll wonder about the difference (even though there's none; it's a trick question!)

I don't have a strong opinion here. If most of us think that the search as is will help, let's add it and iterate.

**Comment by ashutosh-narkar** [comment]
+1 to add the search bar if it doesn't break anything in the docs. Would be a great addition and we can fix issues as they appear.

**Comment by patrick-east** [comment]
> My guess is that redundant results will cause a bit of confusion (and possibly frustration.)

Thats a good point.. I guess in my mind it wasn't a big deal because I knew they were the same results, but for someone new to the project it might be a bad experience. IMO that alone might be enough to hold off until we figure out how to dedupe those.

**Comment by kenfdev** [comment]
I've done a quick research (apologies if this has already tried) and thought if the fix below would work.

In the [docs](https://community.algolia.com/docsearch/tips.html#avoid-duplicates-by-promoting-unicity), they say you can use facets for versioned docs.

>  In cases where the duplicates's existence is expected since it belongs to another dataset (for example a different version), you should use facets.

It seems like you can add a `meta` tag to tell Algolia's crawler which version the document is.

https://community.algolia.com/docsearch/required-configuration.html#introduces-global-information-as-meta-tags

Looking at the config for the Open Policy Agent site [here](https://github.com/algolia/docsearch-configs/blob/master/configs/openpolicyagent.json#L25), it looks like the `version` facet is already set by the crawler (?).

I'm assuming, if the docs can add the `meta` tag for each of the versions (e.g. 0.12.0, 0.11.0, 0.10.7, edge), the facets filtering would work as expected, too. Haven't tried this myself so I'm not sure though  😓

**Comment by kenfdev** [comment]
Thanks for the change @lucperkins ! I did further research and there probably needs to be two more changes for two problems.

1. The `latest` is an alias for the latest version and generates duplicate results
2. Pages with trailing slashes generate duplicate results

For the 1st issue, we can change the `meta` tag when it is the latest version as follows.

`<meta name="docsearch:version" content='["{{ $version }}", "latest"]' />`

I'm not sure if this is possible with hugo. It should only apply when it is the newest version. This is mentioned here.
https://github.com/algolia/docsearch-configs/issues/469#issuecomment-399744126

For the 2nd issue, I think it is the same as the following issue.
https://github.com/algolia/docsearch-configs/issues/744

That said, you can create a PR to the docsearch config like the following PR to stop the crawler to crawl duplicate content.

https://github.com/algolia/docsearch-configs/commit/6f6c5c26f678f6d0f189d5eeb7652ff023e097de

Or, as mentioned in the issue, you can respond with 300 for the duplicate content (the content with the trailing slash maybe?). I'm not sure about what hugo can do here, too.

**Comment by patrick-east** [comment]
@lucperkins / @kenfdev were you guys still looking into this?

**Comment by lucperkins** [comment]
@patrick-east I'm happy to look into this but I think the only viable path is to make incremental changes, i.e. we'll need to go back and forth between changing the OPA site, waiting for those changes to be indexed by Algolia, changing the site, etc. My suggested approach is to make the changes suggested by @kenfdev, merge, and see what happens. If the expectation, however, is that the search works 100% as desired out the gate, I'm not sure there's a good way to get theree.

**Comment by kenfdev** [comment]
@patrick-east I've created a PR to the algolia config for open policy agent here:
https://github.com/algolia/docsearch-configs/pull/961

This should fix the trailing slash duplication problem. As for the `latest` duplication issue, this should be related to an `alias`, but let us see what effect @lucperkins 's fix has with the next crawl.

**Comment by kenfdev** [comment]
I've received an answer saying the docs should properly redirect with status 3XX.
https://github.com/algolia/docsearch-configs/pull/961#pullrequestreview-271975986

It looks like the deploy preview redirects properly (but not the official site):

```
curl -v https://deploy-preview-1513--openpolicyagent.netlify.com/docs/v0.12.2#policy-enablement

...

* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 301
```

So the only way we can see the trailing slash problem being resolved is after this PR gets merged.

I'm closing the PR on the algolia config side. Sorry for the confusion.

**Comment by patrick-east** [comment]
I think the official site would require a change to the netlify config https://www.netlify.com/docs/redirects/#trailing-slash to get those redirects to happen.

**Comment by lucperkins** [comment]
Pretty URLs are already enabled in the site config

**Comment by kenfdev** [comment]
I think everything that can be done on the OPA side has been done but we'll have to merge to see the fixes take effect because the docsearch crawler is crawling the public docs (which doesn't include meta data set in this PR).

If that is not an option, we should ask the algolia team if this PR implementation is correct before merging.

**Pull request merged**
