### PR TITLE
Add new custom integration - GraphQL-Graphene with OPA 

### PR DESCRIPTION
**Pull request by dolevf**
Adding a new integration to OPA ecosystem! Custom application based on Graphene-GraphQL, field level authorization with Open Policy Agent

1. Added integration definition
2. Added logo

### CODE REVIEW

**Review by srenatus — APPROVED** [review]

**Comment by srenatus** [comment]
Trampled on the same section, sorry. 😅 Please also squash three commits, then we can get this merged.

**Comment by dolevf** [comment]
not entirely sure I did it correctly.

**Review by srenatus — APPROVED** [review]
LGTM. Let's squash and merge when green.

**Comment by dolevf** [comment]
@srenatus is that a call for action on my end? I see 5 failing checks but no insight into how these should be addressed.

**Pull request merged**
