### PR TITLE
Bumped wasmtime-go to version 0.40.0 from 0.36.0 and updated the erro…

### PR DESCRIPTION
**Pull request by Parsifal-M**
…r wrapping in vm.go as it was looking for an error message that was no longer present in 0.40.0, now checks if the wasm trap: interrupt is present in the Trap Message which I believe is now the correct message to check for

Signed-off-by: Peter Macdonald <macdonald.peter90@gmail.com>

Hopefully this is okay, but please advise if I've missed something or it does not look quite right.

I've made the changes in the `vm.go` file and ran `make test` multiple times and do not see any errors.

Please let me know what you think of my approach?

Thanks!

### CODE REVIEW

**Review by srenatus — APPROVED** [review]
Thanks!

**Comment by srenatus** [comment]
https://github.com/bytecodealliance/wasmtime-go/issues/151 let's hold it for a bit. We can then go straight to 1.0 and save ourselves one set of library binaries in our guy history 😅

**Comment by srenatus** [comment]
Sorry misclicked

**Comment by srenatus** [comment]
Looks good! Could you please squash the two commits into one and adjust the message? Also take care of dco, please.

Thanks!

**Comment by Parsifal-M** [comment]
> Looks good! Could you please squash the two commits into one and adjust the message? Also take care of dco, please.
> 
> Thanks!

Hey! :wave:

Should be good now?

Thanks again!

**Comment by srenatus** [comment]
Thanks again. I've edited the commit message a bit, hope you don't mind.

**Comment by Parsifal-M** [comment]
> Thanks again. I've edited the commit message a bit, hope you don't mind.

No problem at all!

**Pull request merged**
