### PR TITLE
Add dependency-management-data logo

### PR DESCRIPTION
**Pull request by jamietanna**
### Why the changes in this PR are needed?

Now we've got a logo for the project, we should use it!

### CODE REVIEW

**Comment by charlieegan3** [comment]
Hi Jamie, this looks good to me. the preview is a little funny at https://deploy-preview-6543--openpolicyagent.netlify.app/integrations/dependency-management-data/, but we need to address that with CSS rather than in the PR.

Can you rebase and sign off the commit for the DCO check? then we can get this in.

**Comment by charlieegan3** [comment]
p.s. the new logo is ✨ ! I like it!

**Comment by jamietanna** [comment]
Thanks very much, very happy with it and the designer who did it :smile: 

Ah yes, that looks interesting :sweat_smile:

**Review by charlieegan3 — APPROVED** [review]

**Comment by charlieegan3** [comment]
Thanks for the prompt rebase, I should have a fix in https://github.com/open-policy-agent/opa/pull/6544

**Pull request merged**
