### PR TITLE
Added timestamp

### PR DESCRIPTION
**Pull request by sujanks**

### CODE REVIEW

**Comment by srenatus** [comment]
Hey @sujanks, thanks for contributing!

Just looking at the commit, I could use some context... you seem to be adding a way to have the JSON logs carry timestamps in a certain format...? Could you please go into some detail on what you want to achieve? We could then discuss the best way to implement it. I'd be happy to give you some pointers on how to make such a thing configurable by the ordinary means (OPA's config, not some env variable).

👉 Most of what would be great to add is outlined in [`CONTRIBUTING.md`](https://github.com/open-policy-agent/opa/blob/main/CONTRIBUTING.md#contributing), too.

**Comment by tsandall** [comment]
This has come up in the past; I think the original issue that I filed was in response to someone wanting to limit the timestamp precision: https://github.com/open-policy-agent/opa/issues/2413.

I agree with @srenatus that we should make sure the format is _at least_ provided as a command-line flag and not via an environment variable.

**Comment by tsandall** [comment]
ping @sujanks, any update?

**Comment by tsandall** [comment]
Closing this for now as it's been open for 2 weeks. We can always re-open.

**Pull request closed without merging**
