### PR TITLE
docs: Build html content from integrations.yaml

### PR DESCRIPTION
**Pull request by patrick-east**
This adds in a the HTML view for the integrations.yaml and by having
hugo generate content at build time. It ends up being at the
`/docs/<version/ecosystem` url and there are links to it on the home
page, introduction page, and nav bar under the Misc category.

In future iterations we can add in sorting/filtering etc. It currently
just shows all of them.

Signed-off-by: Patrick East <east.patrick@gmail.com>

### CODE REVIEW

**Comment by patrick-east** [comment]
Once the netlify preview is up check out `/docs/edge/ecosystem/` (open to suggestions for the URL, `/docs/<version>/integrations` is already taken.

We could also not host it inside of `/docs`, its just convenient and in theory opens up having the search bar point people to it.

**Comment by timothyhinrichs** [comment]
This is looking great!  Next steps I'd say are (i) Logos, (ii) Category list or filter.  Categories are important to help people find the integrations they need (no one will read through all the cards), and we'll link to a category from the new website.

**Comment by patrick-east** [comment]
@timothyhinrichs the latest update has logos and some tweaks to the layout. I didn't move forward with the filtering/searching stuff yet.. I'm not sure it needs it right now (it only takes up like 1 page and is pretty easy to visually scan over). If we decide we need it we can make it as an iterative change to keep this PR from getting too big.

**Comment by timothyhinrichs** [comment]
Latest looks awesome!

**Pull request merged**
