### PR TITLE
Changing opa cli flag descriptions to match online docs

### PR DESCRIPTION
**Pull request by OmegaVVeapon**
- Changed the data flag description to specify that it can take policy
or data files
- Suffixed some descriptions with "This flag can be repeated." where
applicable

Fixes: #2586
Signed-off-by: Alan Silva <alansq16@gmail.com>

### CODE REVIEW

**Comment by ashutosh-narkar** [comment]
Thanks @OmegaVVeapon for submitting these changes. We should update the `opa deps` commands to use the `addDataFlag`  and `addBundleFlag` methods similar to the `opa eval` command.  We could also add a long description to the `deps` command similar to `eval` to include usage examples.

**Comment by tsandall** [comment]
@OmegaVVeapon can you update the deps command to use the `addDataFlag` and `addBundleFlag` functions? Once that change is done, we can merge this.

**Comment by OmegaVVeapon** [comment]
Ah, my apologies, I misunderstood the comment w/r/t those functions as a refactor change that would happen separately from this PR. 

I'm no Go developer but I'll give it a try @tsandall .

**Comment by OmegaVVeapon** [comment]
Done. Let me know if the commits are alright.

I also added one more function, the `addOutputFormat` function in the spirit of further unifying the `opa eval` and `opa deps` code.

If that's undesired, I'll revert the commit.

**Pull request merged**
