### PR TITLE
golang: 1.13.7 -> 1.14.9

### PR DESCRIPTION
**Pull request by srenatus**
🤔 I think this one change might be all it takes...? Let's see what CI has to say 😄

### CODE REVIEW

**Comment by srenatus** [comment]
Looks good. WDYT?

**Comment by patrick-east** [comment]
Historically we haven't updated OPAs golang version to try and maintain compatibility for library users with the aim to not force consumers of OPA to update their version. The downside of course being that the OPA binary is being built with an older version, so we lose out on any benefits (or bugs) that come with newer ones.

I could maybe see something like a compatibility ci check where we enforce being able to build/test OPA with an older version, but we _also_ do tests and build the release binaries with a more modern version. Downside being we don't allow new language features (which is usually the motivation to upgrade).

With all that being said maybe it's time to go to 1.14? 😄

**Comment by srenatus** [comment]
Heh, good point. I was expecting something related to that 😅 I don't have anything specific in mind (I do like `t.Cleanup()`, though)...

**Comment by srenatus** [comment]
> I could maybe see something like a compatibility ci check where we enforce being able to build/test OPA with an older version, but we also do tests and build the release binaries with a more modern version. Downside being we don't allow new language features (which is usually the motivation to upgrade).

I think that would be a good compromise.

Also, I just realised the 1.13.x series is at 1.13.15 already 😅

**Comment by srenatus** [comment]
[Release Policy](https://golang.org/doc/devel/release.html#policy):
> Each major Go release is supported until there are two newer major releases.

I think it's time for 1.14 then.

**Comment by srenatus** [comment]
@patrick-east I've pushed a change, it's 1.14.9 now. It's not the bigger leap you've outlined (which I'd like to see, though, too), but gets us to a supported version. 😄

**Comment by anderseknert** [comment]
@srenatus might want to bump the version mentioned [here](https://github.com/open-policy-agent/opa/blob/master/docs/devel/DEVELOPMENT.md) as well. Don't know if there are other places the version is mentioned, I just happened to skim through that document earlier today.

**Comment by srenatus** [comment]
@anderseknert good call, updated!

**Review by patrick-east — APPROVED** [review]
LGTM, thanks @srenatus !

**Pull request merged**
