### PR TITLE
Configurable compiler error reporting

### LINKED ISSUE #249: OPA error reporting should be configurable
OPA error reporting should be configurable.

There are a few use cases where configurable error reporting would be nice:

1. parsing/compiling a large number of modules filled with errors. The output is so large that it becomes unhelpful. In this case, OPA should exit after some configurable number of errors.

2. parsing/compiling fails but certain errors are elided for readability. The OPA developer wants to see all errors.

### PR DESCRIPTION
**Pull request by mmussomele**
Fixes part 1 of #249

### CODE REVIEW

**Comment by tsandall** [comment]
I like the configurable limit on number of errors but I'm not sure about the verbosity changes. There are a few issues that jump to mind.

1. Verbosity may not be boolean, it could be a numeric or enum-based.

2. Verbose flag now has to be propagated throughout the ast package. This is good if you need the flag to make the decision at the error/call site but otherwise it could be handled at a different layer (e.g., before errors are reported.)

3. OPA devs now have to reason about whether their errors should be suppressed by default (or not). I'd rather see failure modes designed carefully so that in all (or the majority of) cases are actionable for the user.

Given that we only have one use case right now (and it's arguable whether it's necessary) let's leave out the verbosity changes. We can always add it later.

**Comment by mmussomele** [comment]
Makes sense, I've removed the second commit.

**Comment by tsandall** [comment]
Tried this out locally and didn't see the expected behaviour, what am I doing wrong?

```
(detached*)torin:~/go/src/github.com/open-policy-agent/opa$ ./opa_darwin_amd64 run
OPA 0.5.3-dev (commit 1de85e99, built at 2017-07-20T23:40:31Z)

Run 'help' to see a list of commands.

> a0=a1;a2=a3;a4=a5;a6=a7;a8=a9;a10=a11;a12=a13
14 errors occurred:
1:1: rego_unsafe_var_error: var a4 is unsafe
1:1: rego_unsafe_var_error: var a10 is unsafe
1:1: rego_unsafe_var_error: var a13 is unsafe
1:1: rego_unsafe_var_error: var a3 is unsafe
1:1: rego_unsafe_var_error: var a7 is unsafe
1:1: rego_unsafe_var_error: var a5 is unsafe
1:1: rego_unsafe_var_error: var a6 is unsafe
1:1: rego_unsafe_var_error: var a8 is unsafe
1:1: rego_unsafe_var_error: var a9 is unsafe
1:1: rego_unsafe_var_error: var a12 is unsafe
1:1: rego_unsafe_var_error: var a0 is unsafe
1:1: rego_unsafe_var_error: var a2 is unsafe
1:1: rego_unsafe_var_error: var a11 is unsafe
1:1: rego_unsafe_var_error: var a1 is unsafe
```

**Comment by mmussomele** [comment]
The query compiler wasn't respecting the compiler's error limit. It should now.

**Pull request merged**
