### PR TITLE
Re-arrange structs for optimal size

### PR DESCRIPTION
**Pull request by anderseknert**
This saves very little in terms of memory consumption (8 bytes for most structs) but on the other hand doesn't cost anything either. The only struct where I think this will make a marginal difference is the Expr one since there can be quite a few of those in a module.

Using https://github.com/orijtech/structslop

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

**Comment by srenatus** [comment]
I'm slightly uneasy about this one. I can't put a finger on an example, but there might have been a reason for putting some field next to the other, and we'd toss that out, for, as you said, little gain.

If we can figure out where it seems worth it, like ast.Expr; or generally some "hot path", then sure, let's do that on those structs 😃

**Comment by anderseknert** [comment]
See the full output of `structslop ./...` below. Even if the saving in terms of size is bigger for some structs I think only the Expr one is common enough to make a difference. I really don't feel strongly about this so I'm fine closing without change.. but on the other hand it doesn't sound great needing to feel uneasy about ordering of structs in this project. Even less so if that meaning has not been encoded in a single test. Both ordering and fields could change over time for other reasons. Anyway - feel free to close.

```shell
/Users/anderseknert/git/opa/opa/ast/policy.go:182:7: struct has size 72 (size class 80), could be 64 (size class 64), you'll save 20.00% if you rearrange it to:
struct {
	With      []*With
	Terms     interface{}
	Location  *location.Location
	Index     int
	Generated bool
	Negated   bool
}

/Users/anderseknert/git/opa/opa/bundle/bundle.go:292:13: struct has size 88 (size class 96), could be 80 (size class 80), you'll save 16.67% if you rearrange it to:
struct {
	loader                DirectoryLoader
	metrics               metrics.Metrics
	baseDir               string
	sizeLimitBytes        int64
	verificationConfig    *VerificationConfig
	files                 map[string]FileInfo
	skipVerify            bool
	includeManifestInData bool
}

/Users/anderseknert/git/opa/opa/topdown/eval.go:38:11: struct has size 424 (size class 448), could be 408 (size class 416), you'll save 7.14% if you rearrange it to:
struct {
	query                  ast.Body
	tracers                []QueryTracer
	store                  storage.Store
	metrics                metrics.Metrics
	seed                   io.Reader
	ctx                    context.Context
	queryCompiler          ast.QueryCompiler
	interQueryBuiltinCache cache.InterQueryCache
	cancel                 Cancel
	genvarprefix           string
	txn                    storage.Transaction
	compiler               *ast.Compiler
	runtime                *ast.Term
	bindings               *bindings
	index                  int
	baseCache              *baseCache
	queryIDFact            *queryIDFactory
	caller                 *eval
	input                  *ast.Term
	data                   *ast.Term
	parent                 *eval
	targetStack            *refStack
	queryID                uint64
	genvarid               int
	time                   *ast.Term
	instr                  *Instrumentation
	builtins               map[string]*Builtin
	builtinCache           builtins.Cache
	virtualCache           *virtualCache
	comprehensionCache     *comprehensionCache
	inliningControl        *inliningControl
	saveSet                *saveSet
	saveStack              *saveStack
	saveSupport            *saveSupport
	saveNamespace          *ast.Term
	external               *resolverTrie
	builtinErrors          *builtinErrors
	plugTraceVars          bool
	traceEnabled           bool
	indexing               bool
	skipSaveNamespace      bool
}

/Users/anderseknert/git/opa/opa/topdown/query.go:28:12: struct has size 352 (size class 352), could be 320 (size class 320), you'll save 9.09% if you rearrange it to:
struct {
	unknowns               []*ast.Term
	time                   time.Time
	tracers                []QueryTracer
	query                  ast.Body
	disableInlining        []ast.Ref
	store                  storage.Store
	interQueryBuiltinCache cache.InterQueryCache
	txn                    storage.Transaction
	genvarprefix           string
	queryCompiler          ast.QueryCompiler
	cancel                 Cancel
	metrics                metrics.Metrics
	partialNamespace       string
	seed                   io.Reader
	runtime                *ast.Term
	builtins               map[string]*Builtin
	instr                  *Instrumentation
	external               *resolverTrie
	input                  *ast.Term
	compiler               *ast.Compiler
	shallowInlining        bool
	skipSaveNamespace      bool
	plugTraceVars          bool
	indexing               bool
	strictBuiltinErrors    bool
}

/Users/anderseknert/git/opa/opa/rego/rego.go:92:18: struct has size 304 (size class 320), could be 288 (size class 288), you'll save 10.00% if you rearrange it to:
struct {
	compiledQuery          compiledQuery
	unknowns               []string
	time                   time.Time
	resolvers              []refResolver
	queryTracers           []topdown.QueryTracer
	parsedUnknowns         []*ast.Term
	disableInlining        []ast.Ref
	txn                    storage.Transaction
	interQueryBuiltinCache cache.InterQueryCache
	parsedInput            ast.Value
	metrics                metrics.Metrics
	partialNamespace       string
	instrumentation        *topdown.Instrumentation
	rawInput               *interface{}
	instrument             bool
	indexing               bool
	hasInput               bool
}

/Users/anderseknert/git/opa/opa/repl/repl.go:38:11: struct has size 336 (size class 352), could be 312 (size class 320), you'll save 9.09% if you rearrange it to:
struct {
	report              [][2]string
	unknowns            []*ast.Term
	buffer              []string
	initPrompt          string
	currentModuleID     string
	target              string
	txn                 storage.Transaction
	metrics             metrics.Metrics
	store               storage.Store
	banner              string
	outputFormat        string
	explain             explainMode
	bufferPrompt        string
	historyPath         string
	output              io.Writer
	errLimit            int
	prettyLimit         int
	modules             map[string]*ast.Module
	runtime             *ast.Term
	mtx                 sync.Mutex
	undefinedDisabled   bool
	instrument          bool
	strictBuiltinErrors bool
	types               bool
	profiler            bool
	bufferDisabled      bool
}

/Users/anderseknert/git/opa/opa/runtime/runtime.go:70:13: struct has size 344 (size class 352), could be 312 (size class 320), you'll save 9.09% if you rearrange it to:
struct {
	Logging                  LoggingConfig
	Paths                    []string
	ConfigOverrideFiles      []string
	ConfigOverrides          []string
	ConfigFile               string
	DiagnosticsBuffer        server.Buffer
	Output                   io.Writer
	ID                       string
	HistoryPath              string
	OutputFormat             string
	ShutdownWaitPeriod       int
	Filter                   loader.Filter
	DiagnosticAddrs          *[]string
	GracefulShutdownPeriod   int
	CertPool                 *x509.CertPool
	Certificate              *tls.Certificate
	DecisionIDFactory        func() string
	Authorization            server.AuthorizationScheme
	Addrs                    *[]string
	Authentication           server.AuthenticationScheme
	BundleVerificationConfig *bundle.VerificationConfig
	ErrorLimit               int
	ReadyTimeout             int
	Watch                    bool
	BundleMode               bool
	EnableVersionCheck       bool
	H2CEnabled               bool
	SkipBundleVerification   bool
	PprofEnabled             bool
}

/Users/anderseknert/git/opa/opa/tester/runner.go:59:13: struct has size 120 (size class 128), could be 112 (size class 112), you'll save 12.50% if you rearrange it to:
struct {
	Trace           []*topdown.Event
	Name            string
	Error           error
	Package         string
	Location        *location.Location
	BenchmarkResult *testing.BenchmarkResult
	Duration        time.Duration
	FailedAt        *ast.Expr
	Skip            bool
	Fail            bool
}

/Users/anderseknert/git/opa/opa/tester/runner.go:113:13: struct has size 120 (size class 128), could be 112 (size class 112), you'll save 12.50% if you rearrange it to:
struct {
	store       storage.Store
	cover       topdown.QueryTracer
	filter      string
	target      string
	compiler    *ast.Compiler
	timeout     time.Duration
	modules     map[string]*ast.Module
	bundles     map[string]*bundle.Bundle
	runtime     *ast.Term
	failureLine bool
	trace       bool
}

/Users/anderseknert/git/opa/opa/cmd/build.go:26:18: struct has size 248 (size class 256), could be 240 (size class 240), you'll save 6.25% if you rearrange it to:
struct {
	entrypoints        repeatedStringFlag
	ignore             []string
	excludeVerifyFiles []string
	scope              string
	pubKey             string
	outputFile         string
	revision           string
	pubKeyID           string
	claimsFile         string
	algorithm          string
	key                string
	capabilities       *capabilitiesFlag
	optimizationLevel  int
	target             *util.EnumFlag
	bundleMode         bool
	debug              bool
}

/Users/anderseknert/git/opa/opa/cmd/eval.go:35:24: struct has size 352 (size class 352), could be 320 (size class 320), you'll save 9.09% if you rearrange it to:
struct {
	dataPaths           repeatedStringFlag
	profileCriteria     repeatedStringFlag
	bundlePaths         repeatedStringFlag
	imports             repeatedStringFlag
	unknowns            []string
	disableInlining     []string
	ignore              []string
	profileLimit        intFlag
	inputPath           string
	prettyLimit         intFlag
	pkg                 string
	schemaPath          string
	outputFormat        *util.EnumFlag
	explain             *util.EnumFlag
	target              *util.EnumFlag
	metrics             bool
	instrument          bool
	stdinInput          bool
	profile             bool
	profileTopResults   bool
	stdin               bool
	strictBuiltinErrors bool
	disableIndexing     bool
	fail                bool
	failDefined         bool
	shallowInlining     bool
	partial             bool
	coverage            bool
}

/Users/anderseknert/git/opa/opa/cmd/test.go:37:24: struct has size 120 (size class 128), could be 104 (size class 112), you'll save 12.50% if you rearrange it to:
struct {
	ignore       []string
	runRegex     string
	errLimit     int
	outputFormat *util.EnumFlag
	count        int
	threshold    float64
	timeout      time.Duration
	explain      *util.EnumFlag
	target       *util.EnumFlag
	bundleMode   bool
	benchmark    bool
	benchMem     bool
	failureLine  bool
	coverage     bool
	verbose      bool
}
```

**Comment by srenatus** [comment]
> but on the other hand it doesn't sound great needing to feel uneasy about ordering of structs in this project. Even less so if that meaning has not been encoded in a single test. Both ordering and fields could change over time for other reasons. 

Sorry I wasn't clear here -- I was thinking about the ordering being the way it is right now for some possible reasons:
1. history -- they just happened to be added at the bottom
2. meaning: some field may make sense as the first one, `runtime.ID`; or next to each other, `runtime.Authentication` and `runtime.Authorization`

All of this would only matter to the human reader; none of these orderings should matter for the compiled software as far as I am concerned. 😃

**Comment by anderseknert** [comment]
Oh, gotcha! Yeah that makes sense. Perhaps just changing `Expr` then would be a good middle ground?

**Comment by tsandall** [comment]
+1 for only changing Expr. Most of the time, fields are declared in an order that makes sense to the author/maintainers (e.g., a bunch of fields related to tracing will be grouped together.)

**Comment by anderseknert** [comment]
@tsandall @srenatus changed to only reorder `Expr`. Now to figure out what to do with all the bytes we've freed up 😆

**Review by srenatus — APPROVED** [review]
Thank you

**Pull request merged**
