### PR TITLE
adding Kubescape to integration page

### PR DESCRIPTION
**Pull request by slashben**

### CODE REVIEW

**Comment by srenatus** [comment]
This preview failure is genuine. Something's off with the new entry. Can't dig in right now. 😬

**Comment by anderseknert** [comment]
I believe it's this:

```yaml
    software:
      - Kubescape
```

since that reference points to nothing in the `software` section in that file.

Also, you'll probably need to use lowercase when referencing the `armo` entry in inventors.

@slashben could you please see if that fixes the build?

**Comment by anderseknert** [comment]
@slashben sorry I wasn't entirely clear. You'll also need to add a section for `kubescape` in the `software` section, just like how you added `armo` to the `organizations` section.

**Comment by slashben** [comment]
> @slashben sorry I wasn't entirely clear. You'll also need to add a section for `kubescape` in the `software` section, just like how you added `armo` to the `organizations` section.

sorry, missed it

**Comment by anderseknert** [comment]
@slashben 

```yaml
    inventors:
      - ARMO
```
☝️ that needs to be made lowercase in order for the system to understand the reference to the entry in the organizations object.

**Review by anderseknert — APPROVED** [review]
LGTM!

**Pull request merged**
