### PR TITLE
1) Added glob.match function to implement glob pattern matching

### PR DESCRIPTION
**Pull request by vrnmthr**
2) Renamed the Regex match function to regex.match (instead of re_match)
3) Renamed regex.globs_match to glob.intersect
4) Modified docs to reference all of the above

All changes are backwards compatible.

Signed-off-by: Varun Mathur <varun.mathur@live.com>

### CODE REVIEW

**Comment by vrnmthr** [comment]
Need to correctly update glide to include github.com/gobwas/glob; I don't quite know how.
I attempted to do it myself, but the build failed with a weird error so I undid all my changes and I will just leave it to you.

**Comment by tsandall** [comment]
@vrnmthr how does this 3rdparty glob library compare to the Go standard library version? https://golang.org/pkg/path/filepath/#Match.

**Comment by vrnmthr** [comment]
[This thread](https://www.reddit.com/r/golang/comments/41ulfq/glob_for_go_works_much_faster_than_regexp_on/)
explains why:
1) it is more feature rich (curly braces support, double wildcards, etc.)
2) compiling increases processing speed

**Comment by tsandall** [comment]
@vrnmthr can you provide more detail on your use case with this built-in function?

Regarding expressiveness, it looks like this package handles a subset of what you can do with regexp.

Regarding performance, the benchmarks in the README claim that it outperforms regexp. At the same time, for low-latency use cases, I would expect that heavy use of built-in functions will be problematic. For these kinds of performance profiles, performance optimizations in OPA itself are much more likely to succeed (see these [blog](https://blog.openpolicyagent.org/partial-evaluation-162750eaf422) [posts](https://blog.openpolicyagent.org/optimizing-opa-rule-indexing-59f03f17caf3) for examples of optimizations in OPA today.) Over time we expect to extend OPA with further optimizations and improve the existing ones to cover more cases.

I'm a bit wary of pulling in this dependency (every single built-in we add needs to be supported indefinitely.) If built-ins wrap the Go standard library, it's much easier to accept them.

Instead of adding this built-in into OPA proper, we could consider adding support for dynamically loaded plugins/built-in functions using [Go's plugin package](https://golang.org/pkg/plugin/). This is something which people have asked for a while now. Let me know if you would be interested in working on this.

**Comment by vrnmthr** [comment]
I thought about it a little and I agree -- it's not fully necessary. For most use cases, Regex should be fine. We can drop this PR for now.

I would definitely be happy to try to put together a first draft for plugins, I'll start working on it and I'll let you know.

**Comment by tsandall** [comment]
Cool! For the plugin support, I think we should extend the runtime package to include a parameter that specifies the directory to load shared libraries out of. When the runtime initializes statically defined plugins, it can also load plugins dynamically out of the directory.

For built-in functions loaded dynamically, the Start() and Stop() functions can be no-ops in most cases.

https://github.com/open-policy-agent/opa/blob/master/runtime/runtime.go

**Pull request closed without merging**
