### PR TITLE
build: Add support for building images based on processor architecture

### PR DESCRIPTION
**Pull request by embesozzi**
Added support for building images based on ARM64 processor architecture. 
I've tested the building image process with the following command:
`make build GOARCH=arm64 GOOS=linux CGO_ENABLED=0 WASM_ENABLED=0`

### CODE REVIEW

**Review by srenatus — APPROVED** [review]
Thanks for looking into this! 👏 

The Makefile change is small enough to not cause worries -- however, merging this will only make it possible for people to build their own arm images. We can publish them as part of our releases without having some sort of CI in place that'll run something on those images (at least smoke tests).

Please fix the DCO sign-off, so we'll be able to merge this.

**Comment by tsandall** [comment]
@embesozzi you'll need to squash your commits and make sure you have signed off. See https://github.com/open-policy-agent/opa/pull/4044/checks?check_run_id=4301189334

**Review by srenatus — APPROVED** [review]
Thanks, all good now. Will merge when green.

**Comment by srenatus** [comment]
@embesozzi FWIW, wasmtime-go has support for linux-aarch64: https://github.com/open-policy-agent/opa/tree/6b3c99f1141107e7d4ff21e9113ec1810c887288/vendor/github.com/bytecodealliance/wasmtime-go/build -- so you could try without disabling cgo+wasm if you're so inclined.

**Pull request merged**
