### PR TITLE
Add Magda to adopters & integration list

### PR DESCRIPTION
**Pull request by t83714**
### Add Magda to adopters & integration list

- Changes:
  - Add [Magda](https://github.com/magda-io/magda) to ADOPTERS.md & docs/website/data/integrations.yaml
  - Add Magda logo

### CODE REVIEW

**Comment by srenatus** [comment]
LGTM! Thanks for adding this.

Can you please take care of the DCO sign-off? Instructions are here: https://github.com/open-policy-agent/opa/pull/4546/checks?check_run_id=5826974108

**Comment by t83714** [comment]
@srenatus Thanks a lot for the DCO sign-off instruction link.
I've just updated my commit. Please let me know if anything else is required 👍

**Review by srenatus — APPROVED** [review]
Thanks

**Comment by srenatus** [comment]
Something's funny with the line breaks in the ecosystem tile, but I don't think it's related to the content, but something to do with the css 🤔 I'll merge this. Thanks again!

**Pull request merged**
