### PR TITLE
Fix import rule. Package should be ref

### LINKED ISSUE #4689: docs: Include part of grammar is incorrect
## Include part of grammar is wrong

https://www.openpolicyagent.org/docs/latest/policy-reference/#grammar

Defines import rules as:

```ebnf
module  = package { import } policy
package = "package" ref
import  = "import" package [ "as" var ]
```

Which means that include rules should look like this:

```rego
package test.package

import package test.include 

...
```

But in practice the `package` part is always omitted.

Should the import rule be `import = "import" ref [ "as" var ]` instead?

### PR DESCRIPTION
**Pull request by mmzeeman**
Small grammar fix in documentation. Fixes #4689

### CODE REVIEW

**Review by srenatus — DISMISSED** [review]
Thanks a bunch 👍

**Comment by srenatus** [comment]
Could you please see after the DCO signed-off-by line? [Details](https://github.com/open-policy-agent/opa/pull/4690/checks?check_run_id=6442794025)

**Comment by mmzeeman** [comment]
Like that?

**Comment by srenatus** [comment]
Exactly. Thanks!

**Comment by srenatus** [comment]
🤦 I've put a typo in the commit message when giving it a small copy-edit. Sorry about that.

**Comment by mmzeeman** [comment]
Ah, such is life.

BTW... I also think there is an error in the `infix-expr` rule... The current form does not allow assignments like `something := true` or `something_else = false`.

**Comment by mmzeeman** [comment]
This rule also does not make any sense.

`ref             = ( var | array | object | set | array-compr | object-compr | set-compr | expr-call ) { ref-arg }`

**Pull request merged**
