### PR TITLE
wasm: Number operands built on arbitrary precision floating points.

### PR DESCRIPTION
**Pull request by koponen-styra**

### CODE REVIEW

**Comment by koponen-styra** [comment]
Dead code elimination while linking is probably worth of exploring -- to guarantee always the smallest binary given the current compiled policy (and its use of builtins).

Is returning NULL sufficient to signal undefined value then?

**Comment by tsandall** [comment]
@koponen-styra yes, a NULL opa_value pointer is considered undefined.

@patrick-east yes, if the `OPA_DUMP_TEST` environment variable is non-empty the test runner will dump the test cases to the directory specified by the environment variable. However, I don't think this has been exercised in about 6 months (since it has to be done manually so YMMV.) I think we're getting close to the point where we'll want to do this. A good starting point would be to dump the tests and then run them with the Golang SDK--there should be no skipped tests (currently a bunch have to be skipped because we don't have built-in support in JS.)

**Comment by tsandall** [comment]
@koponen-styra can you remove rebase on master? It looks like there might be a merge commit from your side that we don't want. I tried using the "Update Branch" feature but the rebase button still says 6 commits will go into master.

Screen Shot 2020-05-05 at 9 07 55 AM

**Comment by koponen-styra** [comment]
I did update branch on github web interface and that introduced the merge commit. Sigh.

**Comment by tsandall** [comment]
We tried this the other day but (i) didn't have multiple commits and (ii) didn't pay attention to the note on the rebase button. Maybe it's a red herring.

**Pull request merged**
