### PR TITLE
ccbr tool join in opa ecosystem

### PR DESCRIPTION
**Pull request by niuzhi**
ccbr tool join in opa ecosystem

update code file: docs/website/data/integerations.yaml

Author:Niu Zhi

### CODE REVIEW

**Comment by philipaconrad** [comment]
Hi there @niuzhi! Thank you for your patience, and thank you for contributing to the OPA ecosystem. :smile: 

You don't need to close/recreate this PR, you can instead `git rebase` it, and that will allow you to update it in-place.

As for why CI is failing, it looks like you have at least 2 issues:
 - [DCO signoff](https://github.com/open-policy-agent/opa/pull/5088/checks?check_run_id=8166253809) for your commits.
 - Some minor YAML issues. (Extra whitespace at the end of a few lines, `category`/`layer` have to be single-word, lower case.)
 
For the git rebase workflow, try something like the following steps, starting from your branch for this PR:
```
# Ensure your branch can be rebased on top of changes on `main`.
git branch --set-upstream-to=origin/main <branchname>
```
```
# Update your local copy of the OPA repo.
git checkout main
git pull
```
```
# Update your branch by rebasing it on top of the changes in `main`.
git checkout <branchname>
git rebase
```
```
# Update your remote branch for the PR.
git push origin <branchname>
```

**Comment by philipaconrad** [comment]
Also, @peteroneilljr @anderseknert, I had some issues trying to build this PR for Netlify locally, and couldn't figure it out for the life of me what the precise YAML issue was after fixing basic formatting stuff. :slightly_frowning_face:  `yamlfmt`'s `-lint` mode didn't show anything obvious that I could tell, and the netlify build tools have just cryptic error messages.

If either of you have a few minutes in the next week or so, could one you take a look at this PR to see if we can figure out what's crashing the Netlify build? I'd love to get this PR rolling again! :smiley:

**Comment by srenatus** [comment]
```
template: docs/ecosystem.html.html:158:37: executing "main" at <partial "docs/integration-org-link.html" (dict "org" . "integrations" $.Site.Data.integrations)>: error calling partial: "/opt/build/repo/docs/website/layouts/partials/docs/integration-org-link.html:1:12": execute of template failed: template: partials/docs/integration-org-link.html:1:12: executing "partials/docs/integration-org-link.html" at <index (index .integrations.organizations .org) "link">: error calling index: index of untyped nil
```
this means that the "organizations" subobject of the integrations yaml is missing a key for the org that's referenced in the new integration. I suspect it's "inventors", and there's no wirelesssecuritylab entry in organizations.

**Comment by srenatus** [comment]
Feel free to reopen when you find the time.

**Pull request closed without merging**
