### PR TITLE
OCI download - Set auth credentials for docker authorizer if needed

### PR DESCRIPTION
**Pull request by carabasdaniel**
Fixes: https://github.com/open-policy-agent/opa/issues/5212

Signed-off-by: carabasdaniel <dani@aserto.com>

### CODE REVIEW

**Comment by srenatus** [comment]
Thanks for picking this up 🎉 Would you think adding a test case is a low-hanging fruit?

**Review by srenatus — DISMISSED** [review]
Thanks

**Comment by srenatus** [comment]
Could you please rebase this? GitHub won't let me do it

**Comment by anderseknert** [comment]
Thank you @carabasdaniel 👍

**Pull request merged**
