### PR TITLE
opa inspect: unhide command

### PR DESCRIPTION
**Pull request by anderseknert**
People aren't going to find it unless we show it's there.

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

**Comment by johanfylling** [comment]
LGTM. Did we figure out if there were no longer any reasons to keep this hidden?

**Review by johanfylling — APPROVED** [review]

**Comment by ashutosh-narkar** [comment]
Afair we kept it hidden to start with so that we could iterate on the result format.

**Comment by anderseknert** [comment]
@ashutosh-narkar should be good to unhide now though, right?

**Comment by ashutosh-narkar** [comment]
> @ashutosh-narkar should be good to unhide now though, right?

Sgtm

**Pull request merged**
