### PR TITLE
docs: Remove extra brackets in "Extending OPA"

### PR DESCRIPTION
**Pull request by gujun4990**
Just remove a extra brackets on "Extending OPA" doc page.

### CODE REVIEW

**Review by srenatus — APPROVED** [review]
Thank you, good catch! 🔍

**Comment by srenatus** [comment]
@gujun4990 I'd be OK merging this as-is, but there seems to be a mismatch in your commit message's email and your github account. If everything was in its right place, this 👇 
image

should show your avatar and link to your github profile.

**Comment by srenatus** [comment]
https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address contains all the details

**Comment by gujun4990** [comment]
OK, I will fix this

**Comment by srenatus** [comment]
Hooray. I'll merge this when green. Thanks for contributing!

**Pull request merged**
