### PR TITLE
Update management-bundles.md

### PR DESCRIPTION
**Pull request by plingam-infy**
docs/content : Management Bundle - Worker Task Pattern over Long Polling  for Bundle Download

### CODE REVIEW

**Review by charlieegan3 — COMMENTED** [review]
Hi @plingam-infy, would you be able to add some detail to the PR description about what the issue is you're hoping to address with these changes? Have you run into some performance challenges while using HTTP long-polling?

**Comment by plingam-infy** [comment]
I have not worked on Long Polling with OPA but my experience with Long Polling is empirical.

Long Polling  limitation with Performance and Scalability is well known.

GO has libraries  to support Long-polling. OPA is leveraging these libs (as OPA is implemented in GO) for policy bundle download.

Would like to know –   what is the rationale behind choosing long polling for policy bundle download from centralized server and storing in in-memory store in OPA instances?
Just because OPA is implemented in GO, it should leverage HTTP long polling. Fallback as Short-polling  may not serve good.

Reverse proxy, gateway, WAF won’t be able to scale easily if there are many long polling connections.

OPA has mentioned in the documentation https://datatracker.ietf.org/doc/html/rfc6202#section-2.2 , which clearly states the above long polling issues.
One more link, though this is for another platform: https://ably.com/topic/long-polling

Worker Task, which is called as “Queue Worker” in Drupal  , shows how to pull the content from centralized server and share updates to the clients.
Queue also supports background asyn processing
Excerpts from https://www.valuebound.com/resources/blog/drupal-queue-worker-api

“Queue is more efficient and can handle resource-intensive tasks. The API also allows you to revert the item back to queue if any failure occurs. Most importantly, you can run multiple queues without interrupting other work.”

One more link about QueueWorker
https://www.drupal.org/project/drupal/issues/3242216

If we have to deploy OPA instances at scale and software infrastructure like  Reverse proxy, gateway, WAF,  can OPA scale with long polling(especially when there are too many bundles to download)?

My suggestion is to implement WorkerTask Pattern as an another  option(in one of the future release of OPA), 
instead of having options only in  long polling and short-polling as fallback(if long polling is not supported).

**Comment by plingam-infy** [comment]
OPA Team,

I have not worked on Long Polling with OPA but my experience with Long Polling is empirical.

Long Polling  limitation with Performance and Scalability is well known.

GO has libraries  to support Long-polling. OPA is leveraging these libs (as OPA is implemented in GO) for policy bundle download.

Would like to know -   what is the rationale behind choosing long polling for policy bundle download from centralized server and storing in in-memory store in OPA instances?
Just because OPA is implemented in GO, it should leverage HTTP long polling. Fallback as Short-polling  may not serve good.

Reverse proxy, gateway, WAF won't be able to scale easily if there are many long polling connections.

OPA has mentioned in the documentation https://datatracker.ietf.org/doc/html/rfc6202#section-2.2 , which clearly states the above long polling issues.
One more link, though this is for another platform: https://ably.com/topic/long-polling

Worker Task, which is called as "Queue Worker" in Drupal  , shows how to pull the content from centralized server and share updates to the clients.
Queue also supports background asyn processing
Excerpts from https://www.valuebound.com/resources/blog/drupal-queue-worker-api

"Queue is more efficient and can handle resource-intensive tasks. The API also allows you to revert the item back to queue if any failure occurs. Most importantly, you can run multiple queues without interrupting other work."

One more link about QueueWorker
https://www.drupal.org/project/drupal/issues/3242216

If we have to deploy OPA instances at scale and software infrastructure like  Reverse proxy, gateway, WAF,  can OPA scale with long polling(especially when there are too many bundles to download)?

My suggestion is to implement WorkerTask Pattern as an another  option(in one of the future release of OPA),
instead of having options only in  long polling and short-polling as fallback(if long polling is not supported).


Thanks
Prakash
Senior Technology Architect | ADMCOE
TOGAF 9.1 Certified Enterprise Architect
AWS |Azure Certified Cloud Architect

**Comment by anderseknert** [comment]
It seems to me that this would be better filed as an issue / feature request than a PR for documentation. The OPA docs are there to document current functionality, not for discussing features for future consideration. If you'd like to open a feature request issue, we could continue this discussion there.

**Comment by plingam-infy** [comment]
Hi,

How to open feature request issue?


Thanks
Prakash

**Comment by ashutosh-narkar** [comment]
@plingam-infy use [this](https://github.com/open-policy-agent/opa/issues/new/choose) for filing a new issue.

**Pull request closed without merging**
