### PR TITLE
Update extensions.md

### PR DESCRIPTION
**Pull request by RmStorm**
Add missing nondeterministic argument to function in docs, see discussion here: https://github.com/orgs/open-policy-agent/discussions/407

### CODE REVIEW

**Review by srenatus — APPROVED** [review]
Thank you!

**Comment by RmStorm** [comment]
I missed another one in the same file :sweat_smile:, exact same case.

**Review by ashutosh-narkar — APPROVED** [review]
Thanks @RmStorm !

**Comment by RmStorm** [comment]
:tada: cool that it's merged! When will the docs actually be updated? During a new release?

**Comment by ashutosh-narkar** [comment]
@RmStorm yes that's correct. For now you can see your changes [here](https://www.openpolicyagent.org/docs/edge/extensions/#custom-built-in-function-in-go).

**Pull request merged**
