### PR TITLE
Add Darwin ARM64 release target

### PR DESCRIPTION
**Pull request by anderseknert**
Somewhat experimental, but now that pretty much all new macs
run with the ARM64 architecture it would be nice to add it as
a target to our releases. Since there is currently no runner
for GitHub Actions (https://github.com/actions/runner/issues/805)
we can't yet run the binary smoke test for this architecture,
but I'm tracking the issue and hoping that can be resolved soon.

Feel free to dismiss this if you think this should wait until later.

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

**Comment by anderseknert** [comment]
At least my manual "smoke test" performed from the build artifact seems to check out :)

https://github.com/open-policy-agent/opa/actions/runs/1515446379#artifacts

**Comment by srenatus** [comment]
Hmm I'm on the fence about this. If an issue is reported about the OPA binary misbehaving on that platform, there won't be anything I can do about it, short of telling them that _you_ will have a look later. 😅 

The situation with windows is not too different, but we've got the ability to run stuff on windows using GHA, so that helps. I'd rather wait for some GHA integration.

It's not too different from #2233. I suppose if we want to broaden our support for more platforms, there would be other options than GHA for doing all the build and tests stuff, but that's a larger endeavour.

I think I'd be OK merging this if we add the proper warning banners for those platforms. Or define some sort of "support tiers".

**Comment by anderseknert** [comment]
> Hmm I'm on the fence about this. If an issue is reported about the OPA binary misbehaving on that platform, there won't be anything I can do about it, short of telling them that you will have a look later. 😅

Haha! That's true. I'm thinking we're pretty much in that situation already though, given how many Mac users probably get their OPA binary via `brew`, which will [build](https://github.com/Homebrew/homebrew-core/blob/master/Formula/opa.rb) the arm64 binary on that platform.

I agree though that this could be marked alpha/beta/experimental in the release notes.

**Comment by srenatus** [comment]
Oh wow, I wasn't aware brew had those 😮 Does brew also do some sort of smoke tests on those platforms...? 🤔

**Comment by srenatus** [comment]
Update: I think they do 👉 https://github.com/Homebrew/homebrew-core/runs/4184771064?check_suite_focus=true

**Comment by anderseknert** [comment]
That's cool! Thanks @srenatus. I suppose they provide their own runner hosted outside of GitHub, right?

```
Current runner version: '2.284.0'
Runner name: 'monterey-arm-2'
Runner group name: 'Default'
Machine name: 'HMBRW-A-001-M1-005'
```

**Comment by srenatus** [comment]
> I suppose they provide their own runner hosted outside of GitHub, right?

Yeah, I suppose so. `12-arm64` is not a "run-on" target I'd seen anywhere else...

**Pull request merged**
