### PR TITLE
 Support Abstract Unix Domain Sockets

### PR DESCRIPTION
**Pull request by amanymous-net**
Fixes: #3533
Signed-off-by: Aman Ali <76710693+amanymous-net@users.noreply.github.com>

### CODE REVIEW

**Comment by amanymous-net** [comment]
sorry about all the git/DCO issues, looks good now

**Comment by tsandall** [comment]
Thanks @amanymous-net. Please squash your commits. We can merge once that's done. I think we might want to document this somewhere (at some point) but since we don't have a section for the server listener stuff, this is fine as is.

**Comment by amanymous-net** [comment]
commits squashed. let me know if i did this wrong, the changes in base branch were throwing me off.

**Comment by ashutosh-narkar** [comment]
@amanymous-net did you run `git fetch upstream` and then `git rebase upstream/main`?  After that force push your commit.

**Comment by amanymous-net** [comment]
> @amanymous-net did you run `git fetch upstream` and then `git rebase upstream/main`? After that force push your commit. Check out the[ development workflow](https://github.com/open-policy-agent/opa/blob/main/docs/devel/DEVELOPMENT.md#workflow) for more info.

Thanks! That helped me figure out where I was messing up.

**Pull request merged**
