### PR TITLE
[WIP] opa server: setup signal handling

### PR DESCRIPTION
**Pull request by flavio**
Handle `SIGINT` and `SIGTERM` inside of opa server. Trigger clean stop of plugins, this ensures decision logs are flushed accordingly.

Fixes issue #780

### CODE REVIEW

**Comment by tsandall** [comment]
@flavio I'm not sure this will address the linked issue. The linked issue was raised by a user that has an interesting deployment model for OPA. Essentially, OPA would be spun up on-the-fly, queried a small number of times to render decisions about a transaction, and then terminated. The problem is that currently OPA's decision logger only uploads batches every n seconds. As a result, the record of those decisions wouldn't be saved in most cases. To workaround this, it seems like could have a mode where OPA waits for the decision logs to upload, but those changes are more complicated. I would also be inclined to put that feature behind a configuration setting.

**Comment by flavio** [comment]
@tsandall I see. I made this change because I noticed the logger plugin waits for all the logs to be pushed when `Stop()` is invoked. Usually the plugin manager invokes the `Stop()` method for each loaded plugin when a "clean exit" happens. A `SIGTERM` or `SIGHUP` would not trigger this code, that's why I'm proposing this change.

Maybe I'm completely wrong about that :smile:

**Comment by tsandall** [comment]
I did not mean to close this.

**Comment by tsandall** [comment]
As it's currently implemented, the logger plugin will wait for a pending upload to complete before stopping but if there are buffered log events & no pending upload, it'll just return. I might be wrong, but that's my current understanding.

I think we should ensure that we have an integration test covering the desired behavior.

**Comment by tsandall** [comment]
@flavio I'm going to close this for now. If you'd like to come back it feel free! Just doing a bit of housekeeping on issues & PRs.

**Pull request closed without merging**
