### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by lucperkins**
This PR fixes some broken links left over from the GitBook system and adds instructions for running a local link check.

### CODE REVIEW

**Comment by tsandall** [comment]
LGTM.

**Comment by tsandall** [comment]
Just need conflicts resolved before we can merge this.

**Comment by lucperkins** [comment]
@tsandall Good to go

**Comment by tsandall** [comment]
hey @lucperkins this looks fine, I'm just curious why all the markdown links are `../<filename-without-extension>` is that a Hugo thing?

**Comment by lucperkins** [comment]
@tsandall Linking to Markdown files won’t work. You have to use the URL of the rendered page. I suspect that it’s an idiosyncrasy of GitBook that it transformed those links into .html links.

**Comment by tsandall** [comment]
Gotcha.

**Pull request merged**
