### PR TITLE
Make version dropdown scrollable

### PR DESCRIPTION
**Pull request by orweis**
Meeting https://github.com/open-policy-agent/opa/issues/3955
(needs to be tested)

### CODE REVIEW

**Comment by tsandall** [comment]
thanks @orweis 🙌 netlify should return to normal momentarily...

**Review by srenatus — DISMISSED** [review]
As far as I could see from a mobile, this works perfectly. Thanks a lot! :clap:

**Comment by orweis** [comment]
Checked (on mobile and desktop)- Looks good to me ;-)
Bombs away.

**Comment by srenatus** [comment]
Still needs the dco signoff, let's merge it then

**Comment by orweis** [comment]
Added another commit with a tweak and the DCO sign-off.
Let me know if something is missing ;-)

**Comment by srenatus** [comment]
Let's squash the commits, too. As of now, only the second one passes the dco check.

**Pull request merged**
