### PR TITLE
[website/docs] Refactor ecosystem page

### PR DESCRIPTION
**Pull request by charlieegan3**
This PR is a refactoring PR and contains no new features. It addresses a number of bugs in the Ecosystem docs page which I wanted to address before making some other changes.

1. Screenshot 2023-06-20 at 10 52 33
2. Screenshot 2023-06-20 at 10 51 50
3. Screenshot 2023-06-20 at 10 51 01
4. Screenshot 2023-06-20 at 10 50 09

Other work done:

* creating a new base template for docs pages and rendering all docs pages including the ecosystem page with this.
* extracting the logic for displaying a list of ecosystem projects from the sorting logic by content counts.

### CODE REVIEW

**Review by srenatus — APPROVED** [review]
LGTM

https://deploy-preview-6029--openpolicyagent.netlify.app/docs/edge/ecosystem/ Is the preview, just as a reminder. It's a known but easily-forgotten thing that the preview's build links to "latest" in the top nav, but only builds "edge"

**Comment by charlieegan3** [comment]
> It's a known but easily-forgotten thing

I have seen this before, but can you remember for which links this happens?

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/opa/blob/main/docs/website/layouts/partials/nav.html#L21

The other top-level pages aren't versioned, but Ecosystem is... you know all this better than I do by now 😅

**Comment by charlieegan3** [comment]
Ahh yes! The homepage links. 👍 

Yeah, having all the versions of the docs under /docs/VERSION makes things a little tricky. /VERSION/docs would have been easier from a Hugo standpoint in some ways but I guess we are where we are now 🙂

**Pull request merged**
