### PR TITLE
docs/website: add Apache APISIX in ecosystem

### PR DESCRIPTION
**Pull request by yzeng25**
Add Apache APISIX to ecosystem.

Signed-off-by: yilin <yzeng25@wisc.edu>

### CODE REVIEW

**Review by anderseknert — APPROVED** [review]
Thanks again! Will merge once the build is green 👍

**Comment by yzeng25** [comment]
> Thanks again! Will merge once the build is green 👍

Yep. Waiting for it :)

**Comment by anderseknert** [comment]
Merged! @yzeng25 Let me know once there are docs on how to use this plugin on the APISIX site, and I will add a link to those too. Will also publish a link on https://github.com/anderseknert/awesome-opa

**Comment by yzeng25** [comment]
> Merged! @yzeng25 Let me know once there are docs on how to use this plugin on the APISIX site, and I will add a link to those too. Will also publish a link on https://github.com/anderseknert/awesome-opa

Awesome! I will keep you updated!

**Pull request merged**
