### PR TITLE
ADOPTERS: added GKE Policy Automation

### PR DESCRIPTION
**Pull request by mikouaj**
Adding GKE Policy Automation to the ADOPTERS file. The tool is already present in the integrations site.

Signed-off-by: Mikolaj Stefaniak <mstefaniak@google.com>

### CODE REVIEW

**Review by srenatus — DISMISSED** [review]
Thanks. LGTM

**Comment by anderseknert** [comment]
@mikouaj it would be awesome if we could get an entry for Google in there! 😃

**Comment by mikouaj** [comment]
@anderseknert you are right, sorry for over-sighting this.
Can't speak for entire Google but I've added an entry for Google Cloud :-)

**Review by anderseknert — APPROVED** [review]
Stellar! Thanks @mikouaj! 👍

**Pull request merged**
