### PR TITLE
Fix wrong windows bundle tar files path separator

### PR DESCRIPTION
**Pull request by shm12**
Fix https://github.com/open-policy-agent/opa/issues/5473

### CODE REVIEW

**Review by srenatus — COMMENTED** [review]
Thanks for looking into this. Do you think there's a way to test this? Our ordinary unit tests aren't run on windows, [but these smoke tests are](https://github.com/open-policy-agent/opa/blob/main/build/binary-smoke-test.sh)...

**Comment by shm12** [comment]
> Thanks for looking into this. Do you think there's a way to test this? Our ordinary unit tests aren't run on windows, [but these smoke tests are](https://github.com/open-policy-agent/opa/blob/main/build/binary-smoke-test.sh)...

Sure, but we will have to have some tar gz tolls installed on the windows machine

**Comment by shm12** [comment]
I have added the test.
You can see in [this workflow](https://github.com/shm12/opa/actions/runs/3699412155) that it fails only on windows, but in the PR it's being fixed

**Review by srenatus — APPROVED** [review]
Thanks

**Pull request merged**
