### PR TITLE
Change Windows download from release link to direct download link

### LINKED ISSUE #2075: The "Download OPA" section in doc Introduction should provide windows binary links
Over on https://www.openpolicyagent.org/docs/latest/#1-download-opa there are URL's and `curl` examples for OSX and Linux, but it says to use the GitHub Releases for windows... there isn't any reason we can't just put a link to the windows binary as well.

This is particularly tricky for someone wanting the `edge` windows binary as it isn't available in the GitHub releases.. they have to either look at the Makefile or guess the URL.

This should be as easy as just adjusting the snippet shown below to instead just say windows binaries are available at `https://openpolicyagent.org/downloads/<version>/opa_windows_amd64.exe` (using the hugo variable for the version).

image

### PR DESCRIPTION
**Pull request by barbia**
Fixes #2075 
Signed-off-by: Anthony Barbieri <anthonyabarbieri@gmail.com>

### CODE REVIEW

**Comment by evrardjp** [comment]
Why was this closed?

**Comment by barbia** [comment]
Hey @evrardjp I opened it thinking I had resolved the issue but the deploy preview convinced me of otherwise. Probably should have moved into WIP. But I probably need a pointer in where to look beyond where I edited.

**Comment by patrick-east** [comment]
@barbia the changes looked good in https://deploy-preview-2123--openpolicyagent.netlify.com/docs/edge/#1-download-opa (note that this only affects the `edge` versioned content, any of the stuff in the markdown files is per-version on the site)

**Comment by barbia** [comment]
ah! got it. thanks for the explanation. reopening, let me know if I need to adjust anything else!

**Pull request merged**
