### PR TITLE
Issue #2306: Removing -l flag from test subcommand

### LINKED ISSUE #2306: Remove -l flag from test subcommand
In 8edf554c6092d2885e2c4feefe00980a11729997 we have marked the `opa test -l` flag as deprecated so we should remove it eventually.

### PR DESCRIPTION
**Pull request by damienjburks**
Fixes #2306

### CODE REVIEW

**Comment by srenatus** [comment]
Thank you! Would you please rebase and squash your commits? When it's only one and that one is properly signed, we can get this merged. Let me know if I can be of assistance with this 😃

**Comment by anderseknert** [comment]
This would leave some dead code in, given how we still keep the `failureLine` param on the params struct, and refer to it in the test, and pass it to both the runner and the reporter. It's just always going to be false. Should we not have it all removed, @srenatus?

**Comment by damienjburks** [comment]
@srenatus it should be fine now. Please check and confirm.

**Comment by damienjburks** [comment]
I'm going to redo this and open another PR with the fixed changes. Sorry for the inconveience.

**Comment by damienjburks** [comment]
Submitted another PR with the requested updates and adjustments. Here is the link: https://github.com/open-policy-agent/opa/pull/4250

**Pull request closed without merging**
