### PR TITLE
example_test: use PartialResult instead of PartialEval

### LINKED ISSUE #2294: Example for PartialResult is using PartialEval
The example for `PartialResult` is using `PartialEval`. Probably a leftover from the deprecation of `PartialEval` https://github.com/open-policy-agent/opa/blob/master/rego/example_test.go#L389

### PR DESCRIPTION
**Pull request by sresthas**
Fixes #2294

### CODE REVIEW

**Comment by patrick-east** [comment]
Thanks @sresthas ! The changes look good.

Can you update the commit message to include `Fixes #2294` similar to what you have in the PR description? (example "ideal" commit message can be seen over in https://github.com/open-policy-agent/opa/blob/master/CONTRIBUTING.md#commit-messages )

**Comment by sresthas** [comment]
@patrick-east done

**Comment by patrick-east** [comment]
Thanks @sresthas ! 

One more little adjustment, can you put the `Fixes #2294` part on a separate line?

As an example if you look at `git log` we would want your commit to look similar to some of these others:

image

Where the first line is a short summary, the next paragraph explains what was changed and why, and then you have the `Fixes: #xxx` line, and last is the DCO sign-off.

This change may not need the longer description (although it is always good to have), so it might look more like this one:

image

**Comment by patrick-east** [comment]
@sresthas can you update the commit message so we can move this ahead?

**Comment by patrick-east** [comment]
Going to close this for now, @sresthas feel free to re-open if/when you are able to continue working on it.

**Pull request closed without merging**
