### PR TITLE
Profile sort options

### PR DESCRIPTION
**Pull request by ecbenezra**
### Why the changes in this PR are needed?

When using `--profile-sort` on opa eval it's not clear from the CLI help what the valid options are.

### What are the changes in this PR?

Add valid options for `--profile-sort` to help command

### CODE REVIEW

**Review by anderseknert — APPROVED** [review]
Thanks for contributing to OPA!

**Review by srenatus — COMMENTED** [review]
It's a great idea to fix that, thank you for your contribution. 🎉 👏 

There's a custom enum flag defined in the OPA code, perhaps we could use that, too? 🤔  Not sure if it would address the discoverability of available options.

**Comment by anderseknert** [comment]
@srenatus I considered that too, but I think the enum values would display in the left column (right?) which if so would likely make that whole column wider, leaving less text for the rightmost column. Not sure we'd want that 🤔

**Review by srenatus — APPROVED** [review]
👍 Fine with me. Thanks again, @ecbenezra  🙌

**Pull request merged**
