### PR TITLE
Fix substring and count unicode handling

### LINKED ISSUE #2799: Built-ins substring and count not unicode aware
## Expected Behavior

`"å" == substring("å", 0, 1)`

## Actual Behavior

`"å" != substring("å", 0, 1)`

```
test := substring("å", 0, 1)
test == "\ufffd" (in REPL)
"test" == "�" (in playground)
```

## Steps to Reproduce the Problem

https://play.openpolicyagent.org/p/TAtYd5ZVYa 

## Additional Info

This was the first and only string function I tried, so there's possibly other string functions not playing nicely with utf-8/unicode.

### PR DESCRIPTION
**Pull request by anderseknert**
This is done by working with the runes directly, both when counting length of strings as well as when slicing them to substrings.

Fixes #2799

Signed-off-by: Anders Eknert <anders.eknert@bisnode.com>

### CODE REVIEW

**Comment by anderseknert** [comment]
About _length_ ... I just noticed that `count` has the same problem:
```
count("åäö") == 6
```
Did not include that in my first series of tests as it's not listed under string functions in the docs but aggregates :)

I'll update the issue and PR to have that included, so you can hold off on reviewing this until then.

**Comment by koponen-styra** [comment]
We should double check the same semantics are followed on the wasm side.

**Comment by anderseknert** [comment]
@koponen-styra tests for unicode handling of WASM built-ins in [this branch](https://github.com/open-policy-agent/opa/commit/d4afaa1caaa7dd4fe5cb657695fd8adb76659176). Looks like a lot more functions are failing there. I don't think my C skills are anywhere near fixing them though 😅 

```
FAIL 018_builtins.json: count built-in string (1): unexpected result
	want: [{"x":3}]
	got : [{"x":6}]
FAIL 018_builtins.json: concat built-in unicode: unexpected result
	want: [{"x":"åäö"}]
	got : [{"x":"Ã¥Ã¤Ã¶"}]
FAIL 018_builtins.json: indexof built-in unicode: unexpected result
	want: [{"x":1}]
	got : [{"x":2}]
FAIL 018_builtins.json: lower built-in unicode: unexpected result
	want: [{"x":"å"}]
	got : [{"x":"Ã¥"}]
FAIL 018_builtins.json: replace built-in unicode: unexpected result
	want: [{"x":"öäö"}]
	got : [{"x":"Ã¶Ã¤Ã¶"}]
FAIL 018_builtins.json: replace_n built-in unicode: unexpected result
	want: [{"x":"aöc"}]
	got : [{"x":"aÃ¶c"}]
FAIL 018_builtins.json: substring built-in unicode: unexpected result
	want: [{"x":"äö"}]
	got : [{"x":"¥Ã"}]
FAIL 018_builtins.json: trim built-in unicode: unexpected result
	want: [{"x":"ä"}]
	got : [{"x":"Ã¤"}]
FAIL 018_builtins.json: trim_left built-in unicode: unexpected result
	want: [{"x":"ö"}]
	got : [{"x":"Ã¶"}]
FAIL 018_builtins.json: trim_prefix built-in unicode: unexpected result
	want: [{"x":"ö"}]
	got : [{"x":"Ã¶"}]
FAIL 018_builtins.json: trim_right built-in unicode: unexpected result
	want: [{"x":"å"}]
	got : [{"x":"Ã¥"}]
FAIL 018_builtins.json: trim_suffix built-in unicode: unexpected result
	want: [{"x":"å"}]
	got : [{"x":"Ã¥"}]
FAIL 018_builtins.json: trim_space built-in unicode: unexpected result
	want: [{"x":"åäö"}]
	got : [{"x":"Ã¥Ã¤Ã¶"}]
FAIL 018_builtins.json: upper built-in unicode: unexpected result
	want: [{"x":"Å"}]
	got : [{"x":"Ã"}]

SUMMARY:
--------
PASS: 287/301
FAIL: 14/301
```

**Comment by tsandall** [comment]
@koponen-styra I haven't looked at the unicode handling on the wasm side lately. How much work is this going to be?

**Comment by koponen-styra** [comment]
> @koponen-styra I haven't looked at the unicode handling on the wasm side lately. How much work is this going to be?

Hopefully this should be fairly simple, the necessary unicode helper functions should be there already. I can look at it.

**Comment by koponen-styra** [comment]
I opened a PR for the wasm fixes: https://github.com/open-policy-agent/opa/pull/2814

Note, that I did not include the wasm tests you had added in your branch; it would be good to have those included in your PR.

**Comment by anderseknert** [comment]
Pushed them just now @koponen-styra .. not sure if you meant all if them or just the ones for count and substring though? I can remove the others if you meant the latter.

**Comment by koponen-styra** [comment]
> Pushed them just now @koponen-styra .. not sure if you meant all if them or just the ones for count and substring though? I can remove the others if you meant the latter.

Ouch, I missed the other builtins. I'll fix them as well, then you can include all of the tests you had.

**Comment by anderseknert** [comment]
@koponen-styra it's fine if you just copy them to your branch/PR - they make more sense there after all :) If not the tests here will be failing until yours is merged and I can rebase from master. Let me know if you do and I'll have it removed from here when I squash the commits.

**Comment by koponen-styra** [comment]
> @koponen-styra it's fine if you just copy them to your branch/PR - they make more sense there after all :) If not the tests here will be failing until yours is merged and I can rebase from master. Let me know if you do and I'll have it removed from here when I squash the commits.

Sure, I can copy the wasm asset tests over and include them with my PR.

**Comment by koponen-styra** [comment]
Ok, I incorporated your tests to https://github.com/open-policy-agent/opa/pull/2814.

**Comment by anderseknert** [comment]
Perfect! This one should be ready for review then :)

**Review by tsandall — APPROVED** [review]
LGTM

**Comment by tsandall** [comment]
GitHub isn't giving me the update branch option :confused: @anderseknert once you rebase on master we can merge this.

**Comment by anderseknert** [comment]
Thanks @tsandall , done 👍

**Review by tsandall — APPROVED** [review]

**Pull request merged**
