### PR TITLE
fix prefix error in `opa inspect` for bundle from root

### PR DESCRIPTION
**Pull request by harikannan512**
Signed-off-by: harikannan512 <harikannan512@gmail.com>

Command used:

Win:  `./opa.exe inspect C:\sample_opa\opa_inspect\ -f json`
Mac: `./opa inspect ~/Downloads/opa_inspect/ -f json`

Resolves:
#5503 

Before:
```
error: bundle Z:\sample_inspect_bundle: manifest roots [a/b/c a/b/d play play2] do not permit data at path '/Z:' (hint: check bundle directory structure)
```

After:
```
{
  "manifest": {
    "revision": "",
    "roots": [
      "a/b/c",
      "a/b/d",
      "play",
      "play2"
    ]
  },
  "signatures_config": {},
  "namespaces": {
    "data": [
      "C:\\sample_opa\\opa_inspect\\/play\\data.json",
      "C:\\sample_opa\\opa_inspect\\/play2\\data.json"
    ],
    "data.a.b.c": [
      "C:\\sample_opa\\opa_inspect\\authz.rego",
      "C:\\sample_opa\\opa_inspect\\authz3.rego"
    ],
    "data.a.b.d": [
      "C:\\sample_opa\\opa_inspect\\authz2.rego"
    ],
    "data.play": [
      "C:\\sample_opa\\opa_inspect\\authz4.rego"
    ]
  }
}
```

If changes from #5508 (resolving the namespace issue) are applied,

After:
```
{
  "manifest": {
    "revision": "",
    "roots": [
      "a/b/c",
      "a/b/d",
      "play",
      "play2"
    ]
  },
  "signatures_config": {},
  "namespaces": {
    "data.a.b.c": [
      "C:\\sample_opa\\opa_inspect\\authz.rego",
      "C:\\sample_opa\\opa_inspect\\authz3.rego"
    ],
    "data.a.b.d": [
      "C:\\sample_opa\\opa_inspect\\authz2.rego"
    ],
    "data.play": [
      "C:\\sample_opa\\opa_inspect\\authz4.rego",
      "C:\\sample_opa\\opa_inspect\\/play\\data.json"
    ],
    "data.play2": [
      "C:\\sample_opa\\opa_inspect\\/play2\\data.json"
    ]
  }
}
```

### CODE REVIEW

**Comment by shm12** [comment]
Hi @harikannan512. Seems like it basically fixes the issue.

I can see a problem though in the output:
```
  "namespaces": {
    "data": [
      "C:\\sample_opa\\opa_inspect\\/play\\data.json",
      "C:\\sample_opa\\opa_inspect\\/play2\\data.json"
    ],
```
The `\\/play` and `\\/play2` path are incorrect. It supposed to be `\\play` and `\\play2` without the leading `/`. I believe it has something to do with the bundle root directory.

**Comment by shm12** [comment]
Also, it's a good opportunity to add a test for it. Take a look here https://github.com/open-policy-agent/opa/pull/5478#pullrequestreview-1214265592

**Comment by harikannan512** [comment]
This commit fixes the file path issue. The new output (with the namespaces fix(#5508)) looks like this:
```
{
  "manifest": {
    "revision": "",       
    "roots": [
      "a/b/c",
      "a/b/d",
      "play",
      "play2"
    ]
  },
  "signatures_config": {},
  "namespaces": {
    "data.a.b.c": [
      "C:\\sample_opa\\opa_inspect\\authz.rego",
      "C:\\sample_opa\\opa_inspect\\authz3.rego"
    ],
    "data.a.b.d": [
      "C:\\sample_opa\\opa_inspect\\authz2.rego"
    ],
    "data.play": [
      "C:\\sample_opa\\opa_inspect\\authz4.rego",
      "C:\\sample_opa\\opa_inspect\\play\\data.json"
    ],
    "data.play2": [
      "C:\\sample_opa\\opa_inspect\\play2\\data.json"
    ]
  }
}
```

Thanks for the reference PR for tests, I'll get to it.

**Comment by harikannan512** [comment]
@shm12 I think I am a bit confused about adding the smoke test. Should I add an example bundle in the `test` package and use the `binary-smoke-test.sh` to add another shell check? I am not sure how this works in windows, but I am assuming given the shebang, it expects bash to exist in the test environment. In which case, it may not work as we are specifically comparing windows formatted path output  

On the other hand, I could enhance some of the existing unit tests with the expected value like so:
```
	expectedFiles := map[string]struct{}{
		"/a/data.json":       {},
		"/policy.rego":       {},
		"/a/b/c/policy.rego": {},
		"/a/.manifest":       {},
	}

```
to look something like this

```
	expectedFiles := map[string]struct{}{
		fmt.Sprintf("%sa%sdata.json", string(os.PathSeparator), string(os.PathSeparator)): {},
		fmt.Sprintf("%spolicy.rego", string(os.PathSeparator)):                            {},
		fmt.Sprintf("%sa%sb%sc%spolicy.rego", string(os.PathSeparator), string(os.PathSeparator),
			string(os.PathSeparator), string(os.PathSeparator)): {},
		fmt.Sprintf("%sa%s.manifest", string(os.PathSeparator), string(os.PathSeparator)): {},
	}

```
so that they look something like this. Not the cleanest solution, so I am open to any opinions and suggestions

**Comment by shm12** [comment]
Hi. The smoke tests runs on the GitHub action windows machine. I believe it uses some bash emulator for windows. I don't really know what you should or shouldn't do. A unit test sounds good anyway though

**Comment by srenatus** [comment]
Thanks for contributing. If we could get some sort of test added here, that would be great. Since it depends on `os.PathSeparator` and we only run the binary smoke tests on Windows, let's add something there.

**Comment by harikannan512** [comment]
closing PR and opening a new PR due to sign off related inconsistencies

**Pull request closed without merging**
