### PR TITLE
Add support for scoped bundles

### PR DESCRIPTION
**Pull request by tsandall**
These changes update OPA to support scoping on bundles. See #1201 for more information. In the future, we can extend scoping so that API callers can declare their own roots.

### CODE REVIEW

**Comment by kfox1111** [comment]
:tada:

**Comment by kfox1111** [comment]
Is there a plan for a released container with this pr in it, soonish?

**Comment by tsandall** [comment]
I just cut v0.10.4 which includes these changes and ought to be on Docker Hub now.

**Comment by kfox1111** [comment]
Great. Thank you.

**Pull request merged**
