### PR TITLE
runtime: Remove --insecure-addr flag

### PR DESCRIPTION
**Pull request by tsandall**
The best kind of diff!

### CODE REVIEW

**Comment by tsandall** [comment]
And then I searched github for "--insecure-addr" and sure enough it's still in the Helm chart: https://github.com/helm/charts/blob/master/stable/opa/templates/deployment.yaml#L72

Sigh. That's a bit annoying. I'm going to close this for now because I suspect it might bite quite  a few people when they upgrade. We should patch the helm chart though.

**Comment by srenatus** [comment]
👉 https://github.com/helm/charts/pull/17947 :point_left:

Looks like this PR could be reopened. WDYT?

**Comment by tsandall** [comment]
Since the helm chart was fixed a year ago, I'd be comfortable with making this breaking change at this point. @patrick-east how do you feel about it?

**Comment by patrick-east** [comment]
That was a year ago? 🤯 

Anyway.. I think we should be ok now 👍

**Pull request closed without merging**
