### PR TITLE
Add note for more recent Kubernetes versions

### PR DESCRIPTION
**Pull request by lawrencegripper**
Minor PR to update the docs for more recent K8s versions as current tutorial will fail.

### CODE REVIEW

**Comment by tsandall** [comment]
@lawrencegripper thanks for submitting this. I think that we're better off just updating the Deployment to use `apps/v1` instead of including a note here. `apps/v1` has been supported in Kubernetes for some time, so I think it's safe to switch. Can you make that change?

**Comment by lawrencegripper** [comment]
Sure, fair warning, I'm in a slightly different path to the doc as I'm using `KIND` not `minikube` so I was a bit worried about updating the file as won't have tested in `minikube`.

**Comment by patrick-east** [comment]
We should update the file, I tried it out quickly on the latest minikube (which deploys kubernetes 1.17.0) and it gives the same error:

```
{10:26} ~ ❯ k apply -f admission-controller.yaml
clusterrolebinding.rbac.authorization.k8s.io/opa-viewer created
role.rbac.authorization.k8s.io/configmap-modifier created
rolebinding.rbac.authorization.k8s.io/opa-configmap-modifier created
service/opa created
configmap/opa-default-system-main created
error: unable to recognize "admission-controller.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
```

I think as-is the docs are just incompatible with 1.16+ (which, i think, is when they removed the deprecated API and now require using the newer apps/v1 deployment API)

**Comment by lawrencegripper** [comment]
I've updated the `deployment` to use `apps/v1` and also updated the intro to recommend either `kind` or `minikube` and `v1.13+`. 

Interestingly I couldn't find a nice table anywhere of which releases of `k8s` supported `apps/v1` so went backwards through the release docs until the page disappeared. 

https://v1-13.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/ -> https://v1-12.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/

**Pull request merged**
