### PR TITLE
Show latest docs in preview build

### PR DESCRIPTION
**Pull request by lucperkins**

### CODE REVIEW

**Comment by tsandall** [comment]
@lucperkins this is exactly what I was going to ask for :sweat_smile: 

Let me know when it's ready to go.

**Comment by lucperkins** [comment]
@tsandall Haha yesss 👌🏼It should be ready to go if the preview build looks right.

**Comment by tsandall** [comment]
In the preview, the frontpage links to the docs 404 and manually pointing the browser at the docs base URL also 404s.

**Comment by lucperkins** [comment]
@tsandall Okay, this should be good to go now

**Comment by tsandall** [comment]
@lucperkins looks good. There are some conflicts. Once those are fixed we can merge.

**Comment by lucperkins** [comment]
@tsandall Hmm, not seeing any conflicts. Good to go 👍

**Comment by tsandall** [comment]
Still seeing the conflicts. Screenshot from 2019-04-06 12-17-38

I'm going to submit a new PR based on your changes because I'd love to see this land ASAP.

**Comment by lucperkins** [comment]
@tsandall Huh, weird. I’ve never seen conflicts like that in the UI. I don’t have my laptop handy so feel free to submit a separate PR if you’d like.

**Comment by tsandall** [comment]
No worries. It's fixed in #1320. Closing this one.

**Pull request closed without merging**
