### PR TITLE
Integrating env0 as an integration tool

### PR DESCRIPTION
**Pull request by yarivg**
env0 supports OPA, and has rich guides explaining how to use it on the platform. So it's time to be listed as part of the integration tools on your site 👍  

### Why the changes in this PR are needed?
Adding information based on the schema in [this guide](https://github.com/open-policy-agent/opa/tree/main/docs#opa-ecosystem)

### What are the changes in this PR?
env0's image and integration information

### CODE REVIEW

**Comment by ashutosh-narkar** [comment]
@yarivg thanks for the submission. Can you please squash and sign-off your commit and we can get this in. Thanks.

**Comment by yarivg** [comment]
> @yarivg thanks for the submission. Can you please squash and sign-off your commit and we can get this in. Thanks.

@ashutosh-narkar done ✅

**Comment by anderseknert** [comment]
@yarivg can you please rebase against latest main? I don't seem to be able to do so from the UI, likely because of some setting in your fork.

Screenshot 2024-04-03 at 10 53 07

**Comment by charlieegan3** [comment]
I have a small update in https://github.com/open-policy-agent/opa/pull/6663/files#diff-690a6306ad2d68ebeae50626febef7763d5ec8b8e1f11e3230ee609bd20e437bR32 that will get this integration on the terraform page too. (https://www.openpolicyagent.org/ecosystem/terraform/)

**Pull request merged**
