### PR TITLE
Updated Styra Logo

### PR DESCRIPTION
**Pull request by peteroneilljr**
Update Styra DAS Logo
Signed-off-by: Peter ONeill <peteroneilljr@gmail.com>

### CODE REVIEW

**Comment by anderseknert** [comment]
That's not the logo used for the ecosystem page. You'll want to update the one at:

```
docs/website/static/img/logos/integrations/styra-das.png
```
Make sure to keep the name intact though.

**Comment by srenatus** [comment]
The logo file that was replaced here was only used in the support page:
image

If think we should make it larger there -- as of now, it's a little hard to read. Replacing the logo on that page seems fine, though.

**Comment by anderseknert** [comment]
@srenatus I would argue that replaceing the logo there isn't necessary, given how the same text is repeated just to the right :)

**Comment by srenatus** [comment]
🤷 Can't hurt. But yeah, fine either way.

**Comment by peteroneilljr** [comment]
Updated the correct logo this time :)

**Review by anderseknert — APPROVED** [review]

**Pull request merged**
