### PR TITLE
bump: go 1.19.5 -> 1.20

### PR DESCRIPTION
**Pull request by srenatus**
https://go.dev/doc/go1.20

Also bumping golangci-lint for support with go1.20.

### CODE REVIEW

**Comment by srenatus** [comment]
🚧 Two fixes needed: random seed, and the x509 system pool.

**Comment by philipaconrad** [comment]
@srenatus @ashutosh-narkar I've dealt with the 2x categories of issue that came up:

- For the PRNG seed issue, we've migrated to the recommended alternative. (~6x callsites)
- For the x509 system pool, I've gone with linter ignores, since it's only present in tests, and this seems to be approach taken by other large projects. (8x callsites)

The random red removed blank lines are from my editor's automatic `gofmt` being a bit overzealous about removing excess whitespace, and should not be semantically significant.

**Comment by philipaconrad** [comment]
The failing tests seem to be caused by some difference in how TLS certificate verification works now, I think? I haven't had time to triage it further, but at least we're not breaking at the linter stage now. :sweat_smile:

**Comment by philipaconrad** [comment]
Force-push was for a rebase to track the state of `main`.

`go.mod`/`go.sum` merge conflicts were resolved by accepting incoming changes, and then running `go mod tidy` immediately thereafter.

**Comment by philipaconrad** [comment]
Well, at least it's down to a smaller set of things exploding. Still have `go.sum` issues. :disappointed:

**Comment by ashutosh-narkar** [comment]
Bumping Go to `1.20.1` in [this](https://github.com/open-policy-agent/opa/pull/5672) PR to address the following vulnerabilities:

https://pkg.go.dev/vuln/GO-2023-1571
https://pkg.go.dev/vuln/GO-2023-1570
https://pkg.go.dev/vuln/GO-2023-1568

**Comment by ashutosh-narkar** [comment]
Closing in favor of https://github.com/open-policy-agent/opa/pull/5672.

**Pull request closed without merging**
