### PR TITLE
Apply credentials masking on opa.runtime().config

### LINKED ISSUE #4159: Apply masking on opa.runtime().config values
## What part of OPA would you like to see improved?

Similarly to how we mask certain values like secrets at the `/v1/config` endpoint, I'd like to see the same masking applied to the attributes returned by `opa.runtime().config`

## Describe the ideal solution

The above.

## Describe a "Good Enough" solution

https://github.com/open-policy-agent/opa/issues/4153

Although disabling `opa.runtime()` isn't going to be ideal in many cases, like when reading some env vars is required.

## Additional Context

Related: https://github.com/open-policy-agent/opa/issues/4156

### PR DESCRIPTION
**Pull request by anderseknert**
In order to prevent sensitive data to accidentally
leak out into policies, reuse masking logic previously
serving the /v1/config endpoint.

Fixes #4159

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

**Comment by srenatus** [comment]
We didn't care for backwards compatibility with the config change, I think, because it's clearly been undesirable there. Is this as clear-cut, what do you think? Would anyone want the previous behaviour?

**Review by srenatus — APPROVED** [review]
LGTM. Do we need extra care for certificate keys? E.g. opentelemetry's tls config?

**Comment by anderseknert** [comment]
> opentelemetry's tls config

That's interesting. I hadn't considered that. Looking at the [config options](https://www.openpolicyagent.org/docs/edge/configuration/#distributed-tracing) though, it seems to be only pointing at file paths, and not carrying the actual keys. That seems acceptable to me.

**Comment by anderseknert** [comment]
As for backwards compatibility, yeah I can _maybe_ see how someone would reuse e.g. OAuth2 credentials from the config to also fetch tokens from an authorization server inside a policy. But I think that would be unusual enough to still warrant the change in order to provide secure, non-leaky, defaults.

What I'm not as sure about though is the copy-pasta from config.go ... it seems like it will be difficult enough to remember updating this in one place in the future should new credentials be added, let alone two places. Do you think it would make sense to add a new standalone PurgeConfig function in config.go which we could call from both places?

**Pull request merged**
