### PR TITLE
Add missing YAML files used in docs

### PR DESCRIPTION
**Pull request by lucperkins**
These two YAML files were recently removed from the documentation sources. Unfortunately, these files are necessary to build an earlier version of the documentation (v0.10.6).

### CODE REVIEW

**Comment by tsandall** [comment]
@lucperkins I didn't realize that `code` (like `layouts`) was outside of versioning. I'm a bit worried about this because it means that whenever we change non-markdown files under docs, we need to consider the impact on past versions of the site. I'd much rather have the versioning based off Git.

E.g., to produce docs for version X you checkout tag X and execute a make target. To produce a site with docs for previous versions you iterate over the list of versions/tags.

**Comment by lucperkins** [comment]
@tsandall Yeah, it was an oversight on my part but I'm not sure how to rectify that given the immutability of past tags.

**Comment by tsandall** [comment]
Where does the problem caused by these missing files crop up. I'm looking at https://openpolicyagent.netlify.com/docs/v0.10.6/kubernetes-admission-control/ and https://openpolicyagent.netlify.com/docs/v0.10.6/deployments/ and the content appears to be there (though it seems be the latest.)

**Comment by lucperkins** [comment]
I’m honesty not quite sure why it’s working, as it’s broken for me locally. But if it’s working in prod, I suppose we can just let it be.

**Pull request merged**
