### PR TITLE
Add Sansshell entry to OPS integrations

### PR DESCRIPTION
**Pull request by sfc-gh-jchacon**

### CODE REVIEW

**Comment by srenatus** [comment]
Let's fix dco so we can get this merged: https://github.com/open-policy-agent/opa/pull/4674/checks?check_run_id=6359819172

**Comment by anderseknert** [comment]
This is great!

**Comment by sfc-gh-jchacon** [comment]
How do I fix dco?

**Comment by sfc-gh-jchacon** [comment]
Ok, DCO is happy now

**Review by srenatus — APPROVED** [review]
LGTM. I'd have expected a logo but there isn't one for the project yet it seems. 👍

**Pull request merged**
