### PR TITLE
[#6003] Update otel to v1.16.0

### PR DESCRIPTION
**Pull request by ghaskins**
Fixes issue #6003

### Why the changes in this PR are needed?

Applications using the latest otel (v1.16.0 at the time of writing) cannot currently also use OPA without introducing transitive conflicts with the OPA dependency on otel v1.14.0, at least from a 'go mod tidy' perspective.

### What are the changes in this PR?

Update the otel dependency to the latest (v1.16.0) and run any peripheral tasks related to this, such as updating the vendor cache.

### Further comments:

Reference: https://github.com/temporalio/temporal/pull/4481

### CODE REVIEW

**Comment by ashutosh-narkar** [comment]
@ghaskins thanks for looking into this. Can you please look into the test failures? It seems like some span attributes are different as a result of the lib update.

**Comment by ghaskins** [comment]
@ashutosh-narkar Apologies.  I can look at that.  One of the problems I was having was even the main-branch tests failed for me on my Mac, so I didn't have a way to know if what I submitted would pass or not without pushing to GitHub.  I hoped it would magically pass when I did, but I was not lucky enough for that to be the case.

I will figure out how to get to a baseline passing state, then apply my PR on top and see what is happening.

**Comment by ashutosh-narkar** [comment]
@ghaskins we've been noticing some tests flakiness recently and we're looking to resolve that. The error in that case is something like:
```
1 error occurred: /tmp/opa_test1117885614/test.rego:7: rego_type_error: match error
	left  : boolean
	right : number
PASS: 1/1
1 error occurred: /tmp/opa_test3018394937/test.rego:6: rego_type_error: match error
	left  : boolean
	right : number
1 error occurred during loading: /tmp/opa_test2892591158/data.json: EOF
FAIL	github.com/open-policy-agent/opa/cmd	22.061s
```

So if your tests result in the above error it's probably not due to your changes.

**Comment by ghaskins** [comment]
@ashutosh-narkar That is helpful, thank you.  I will take a look.

**Comment by srenatus** [comment]
So, I've started chasing these up. Found out about the `http.scheme` removal from _client spans_ [here](https://github.com/open-telemetry/opentelemetry-go/issues/3528#issuecomment-1374196644):
> We no longer add the `http.schema` attribute to HTTP client spans.

This means it's all intentional and can be traced back to that discussion, so we should update `TestClientSpans` accordingly.

I have yet to find out more about the change in _server_ spans, missing `http.host`

**Comment by ashutosh-narkar** [comment]
@ghaskins would you be able to look into the missing/updated spans and the resulting test failures? Please let us know if you need any help.

**Comment by ghaskins** [comment]
@ashutosh-narkar I can try.  I am not familiar with the OPA code base so it may take a bit for me to wrap my head around it.

**Comment by ashutosh-narkar** [comment]
> @ashutosh-narkar I can try. I am not familiar with the OPA code base so it may take a bit for me to wrap my head around it.

Sure thanks for the update @ghaskins. Let us know if you have any questions.

**Comment by anderseknert** [comment]
I stumbled upon this when trying to update https://github.com/open-policy-agent/example-api-authz-go the other day. FWIW, your work on this is appreciated @ghaskins 👍

**Comment by zregvart** [comment]
This helped on my end with the test failures, @ghaskins can you try to include this in?

```diff
diff --git a/test/e2e/distributedtracing/distributedtracing_test.go b/test/e2e/distributedtracing/distributedtracing_test.go
index 6fea8c77a..d34367ecb 100644
--- a/test/e2e/distributedtracing/distributedtracing_test.go
+++ b/test/e2e/distributedtracing/distributedtracing_test.go
@@ -9,7 +9,9 @@ import (
 	"flag"
 	"fmt"
 	"net/http"
+	"net/url"
 	"os"
+	"strconv"
 	"strings"
 	"testing"
 
@@ -68,21 +70,32 @@ func TestServerSpan(t *testing.T) {
 		if !spans[0].SpanContext.IsValid() {
 			t.Fatalf("invalid span created: %#v", spans[0].SpanContext)
 		}
+		if got, expected := spans[0].Name, "v0/data"; got != expected {
+			t.Fatalf("Expected span name to be %q but got %q", expected, got)
+		}
 		if got, expected := spans[0].SpanKind.String(), "server"; got != expected {
 			t.Fatalf("Expected span kind to be %q but got %q", expected, got)
 		}
 
+		u, err := url.Parse(testRuntime.URL())
+		if err != nil {
+			t.Fatal(err)
+		}
+		port, err := strconv.Atoi(u.Port())
+		if err != nil {
+			t.Fatal(err)
+		}
 		expected := []attribute.KeyValue{
-			attribute.String("http.host", strings.Replace(testRuntime.URL(), "http://", "", 1)),
+			attribute.String("net.host.name", u.Hostname()),
+			attribute.Int("net.host.port", port),
 			attribute.String("http.method", "POST"),
 			attribute.String("http.scheme", "http"),
-			attribute.String("http.server_name", "v0/data"),
+			attribute.String("http.flavor", "1.1"),
 			attribute.Int("http.status_code", 200),
-			attribute.String("http.target", "/v0/data"),
 			attribute.String("http.user_agent", "Go-http-client/1.1"),
 			attribute.Int("http.wrote_bytes", 3),
-			attribute.String("net.transport", "ip_tcp"),
 		}
+
 		compareSpanAttributes(t, expected, attribute.NewSet(spans[0].Attributes...))
 	})
 
@@ -102,20 +115,30 @@ func TestServerSpan(t *testing.T) {
 		if !spans[0].SpanContext.IsValid() {
 			t.Fatalf("invalid span created: %#v", spans[0].SpanContext)
 		}
+		if got, expected := spans[0].Name, "v1/data"; got != expected {
+			t.Fatalf("Expected span name to be %q but got %q", expected, got)
+		}
 		if got, expected := spans[0].SpanKind.String(), "server"; got != expected {
 			t.Fatalf("Expected span kind to be %q but got %q", expected, got)
 		}
 
+		u, err := url.Parse(testRuntime.URL())
+		if err != nil {
+			t.Fatal(err)
+		}
+		port, err := strconv.Atoi(u.Port())
+		if err != nil {
+			t.Fatal(err)
+		}
 		expected := []attribute.KeyValue{
-			attribute.String("http.host", strings.Replace(testRuntime.URL(), "http://", "", 1)),
+			attribute.String("net.host.name", u.Hostname()),
+			attribute.Int("net.host.port", port),
 			attribute.String("http.method", "GET"),
 			attribute.String("http.scheme", "http"),
-			attribute.String("http.server_name", "v1/data"),
+			attribute.String("http.flavor", "1.1"),
 			attribute.Int("http.status_code", 200),
-			attribute.String("http.target", "/v1/data"),
 			attribute.String("http.user_agent", "Go-http-client/1.1"),
 			attribute.Int("http.wrote_bytes", 67),
-			attribute.String("net.transport", "ip_tcp"),
 		}
 		compareSpanAttributes(t, expected, attribute.NewSet(spans[0].Attributes...))
 	})
@@ -271,11 +294,10 @@ func TestClientSpan(t *testing.T) {
 
 		expected := []attribute.KeyValue{
 			attribute.String("http.method", "GET"),
-			attribute.String("http.url", testRuntime.URL()+"/health"),
-			attribute.String("http.scheme", "http"),
-			attribute.String("http.host", strings.Replace(testRuntime.URL(), "http://", "", 1)),
 			attribute.String("http.flavor", "1.1"),
+			attribute.String("http.url", testRuntime.URL()+"/health"),
 			attribute.Int("http.status_code", 200),
+			attribute.Int("http.response_content_length", 3),
 		}
 		compareSpanAttributes(t, expected, attribute.NewSet(spans[1].Attributes...))
 	})
@@ -314,11 +336,10 @@ func TestClientSpan(t *testing.T) {
 
 		expected := []attribute.KeyValue{
 			attribute.String("http.method", "GET"),
-			attribute.String("http.url", testRuntime.URL()+"/health"),
-			attribute.String("http.scheme", "http"),
-			attribute.String("http.host", strings.Replace(testRuntime.URL(), "http://", "", 1)),
 			attribute.String("http.flavor", "1.1"),
+			attribute.String("http.url", testRuntime.URL()+"/health"),
 			attribute.Int("http.status_code", 200),
+			attribute.Int("http.response_content_length", 3),
 		}
 		compareSpanAttributes(t, expected, attribute.NewSet(spans[1].Attributes...))
 
@@ -364,11 +385,10 @@ func TestClientSpan(t *testing.T) {
 
 		expected := []attribute.KeyValue{
 			attribute.String("http.method", "GET"),
-			attribute.String("http.url", testRuntime.URL()+"/health"),
-			attribute.String("http.scheme", "http"),
-			attribute.String("http.host", strings.Replace(testRuntime.URL(), "http://", "", 1)),
 			attribute.String("http.flavor", "1.1"),
+			attribute.String("http.url", testRuntime.URL()+"/health"),
 			attribute.Int("http.status_code", 200),
+			attribute.Int("http.response_content_length", 3),
 		}
 		compareSpanAttributes(t, expected, attribute.NewSet(spans[1].Attributes...))
 
@@ -417,11 +437,10 @@ func TestClientSpan(t *testing.T) {
 
 		expected := []attribute.KeyValue{
 			attribute.String("http.method", "GET"),
-			attribute.String("http.url", testRuntime.URL()+"/health"),
-			attribute.String("http.scheme", "http"),
-			attribute.String("http.host", strings.Replace(testRuntime.URL(), "http://", "", 1)),
 			attribute.String("http.flavor", "1.1"),
+			attribute.String("http.url", testRuntime.URL()+"/health"),
 			attribute.Int("http.status_code", 200),
+			attribute.Int("http.response_content_length", 3),
 		}
 		compareSpanAttributes(t, expected, attribute.NewSet(spans[1].Attributes...))
 	})
@@ -606,21 +625,28 @@ allow {
 		if !spans[0].SpanContext.IsValid() {
 			t.Fatalf("invalid span created: %#v", spans[0].SpanContext)
 		}
-
+		if got, expected := spans[0].Name, server.PromHandlerAPIAuthz; got != expected {
+			t.Fatalf("Expected span name to be %q but got %q", expected, got)
+		}
 		if got, expected := spans[0].SpanKind.String(), "server"; got != expected {
 			t.Fatalf("Expected span kind to be %q but got %q", expected, got)
 		}
 
+		u := mr.Request.URL
+		port, err := strconv.Atoi(u.Port())
+		if err != nil {
+			t.Fatal(err)
+		}
+
 		expected := []attribute.KeyValue{
-			attribute.String("http.host", strings.Replace(rt.URL(), "http://", "", 1)),
+			attribute.String("net.host.name", u.Hostname()),
+			attribute.Int("net.host.port", port),
 			attribute.String("http.method", "POST"),
 			attribute.String("http.scheme", "http"),
-			attribute.String("http.server_name", server.PromHandlerAPIAuthz),
+			attribute.String("http.flavor", "1.1"),
 			attribute.Int("http.status_code", 401),
-			attribute.String("http.target", "/v1/data"),
 			attribute.String("http.user_agent", "Go-http-client/1.1"),
 			attribute.Int("http.wrote_bytes", 87),
-			attribute.String("net.transport", "ip_tcp"),
 		}
 		compareSpanAttributes(t, expected, attribute.NewSet(spans[0].Attributes...))
 

```

**Comment by srenatus** [comment]
Thanks for contributing @zregvart! I think it's the right call to adjust our tests. OpenTelemetry is evolving, and there's not much to be done against that (nothing we can do and no reason to do anything) -- so we'll just follow along their path. 👍

**Comment by ghaskins** [comment]
I'll try to pull this in tonight and see where I get.

**Comment by gr0l0rg** [comment]
I really really really hope this get merged and release very soon.

**Comment by srenatus** [comment]
> I really really really hope this get merged and release very soon.

I'm afraid the next release is underway. So this could have to wait -- but I'm sure we can do a 0.54.1 release for this if need be.

**Comment by gr0l0rg** [comment]
@srenatus It's unfortunate this all has to happen because of Golang's inexplicably mediocre package management. OTEL breaking changes destroy my binaries on a monthly basis.

**Comment by srenatus** [comment]
> @srenatus It's unfortunate this all has to happen because of Golang's inexplicably mediocre package management. OTEL breaking changes destroy my binaries on a monthly basis.

I see what I can do about this, for now.

**Comment by gr0l0rg** [comment]
@srenatus Thank you for your quick response. I would extremely appreciate if you could publish a new release with this merge ASAP. Fixing OTEL constant breaking changes is just a nightmare if they are indirectly imported in your dependencies.

**Comment by srenatus** [comment]
I'll finish this here: https://github.com/open-policy-agent/opa/pull/6062 Thanks a lot @ghaskins and @zregvart! 👏 🥳

**Comment by srenatus** [comment]
ℹ️ Here's the plan: We cannot bump OTel without dropping support for Golang 1.18. So what we're going to do is:
1. Release 0.54.0 (very soon) without OTel 1.16, but with a note saying that it's the last release of OPA that builds with Golang 1.18
2. Release 0.54.1 (very soon after) with OTel 1.16, without support for Golang 1.18; with a note saying that the only change over 0.54.0 is OTel.

That should do the trick -- 🤞 as long as there's no other urgent patch release need until 0.55.0. But let's worry about that when it happens.

**Comment by srenatus** [comment]
@zregvart @ghaskins @gr0l0rg @mavinkite (👋) -- Would you be able to just use `main`? It only now occurred to me that you might not need a release to build from source anyways.

**Comment by srenatus** [comment]
Could you please try `go get github.com/open-policy-agent/opa@1fc95f43f8b1ebbfb543869b659564cd63d5eff6`?

**Comment by gr0l0rg** [comment]
@srenatus Thank you! it now works perfectly. It got translated into the go.mod file so you may want to import it as `go get github.com/open-policy-agent/opa@v0.54.1-0.20230630073603-1fc95f43f8b1`

**Comment by srenatus** [comment]
OK let's update our plan then: If you need OTel 1.16.0, please use the main reference that @gr0l0rg has shared ☝️ We will **not** do a patch release. This is a good and stable workaround. The next release of OPA, 0.55.0 (end of July), will include this change, too, and **drop support for Golang 1.18**.

**Comment by ghaskins** [comment]
> @zregvart @ghaskins @gr0l0rg @mavinkite (👋) -- Would you be able to just use `main`? It only now occurred to me that you might not need a release to build from source anyways.

I can confirm the fix as prescribed but I probably can't use it for real until an official release comes out as I am PR'ing a different project (https://github.com/temporalio/temporal/pull/4481) and I suspect they will require a real tag.

Thank you so much for driving this over the finish line.

**Comment by srenatus** [comment]
@ghaskins let's discuss it with temporal, maybe? If this becomes the last thing blocking a merge, I'll cut you a 0.54.1 release 🤞

**Comment by ghaskins** [comment]
A patch release would be appreciated.  So far, I've not received any feedback from the Temporal folks on my proposal or PR, so I don't know whether there is an appetite to consider it at all, much less within the timeframe of a July release of OPA.  However, clearing the CI failure in my PR probably at least removes one barrier to get a review.  Thanks again for driving this.

**Pull request closed without merging**
