### PR TITLE
custom reason in authz policy

### PR DESCRIPTION
**Pull request by srenatus**
I've taken over with #3078; updating test docs and the test according to nitpicks. The bulk of the work is @ajanthan's!

📢 @ajanthan: I hope you don't mind me running with this!

### CODE REVIEW

**Review by tsandall — DISMISSED** [review]
LGTM modulo netlify build issue.

**Comment by srenatus** [comment]
If the "json with comments" looks OK on netlify, I'll merge this. I've got my doubts based on how it looks on GH:

image

Better or worse than before? I'm not sure. Both terrible:

image


(For reference: https://github.com/github/linguist/pull/4171/files is what made github markdown accept it)

**Comment by srenatus** [comment]
👇 It makes **no difference** in how the json with comments looks on netlify. So, let's keep it. 🤷 

image

**Comment by tsandall** [comment]
SGTM

**Pull request merged**
