### PR TITLE
Add additional syntax highlighting options

### PR DESCRIPTION
**Pull request by lucperkins**
The changes in this PR enable you to programmatically create code blocks with line numbers and side-by-side code "panes."

You can see this in action on [Kubernetes Admission Control](https://deploy-preview-1317--openpolicyagent.netlify.com/docs/guides-kubernetes-admission-control/) guide.

cc @tsandall

### CODE REVIEW

**Comment by tsandall** [comment]
This is a welcome change though I wish site generators like Hugo played nicer with Markdown (because if you look at the Markdown inside an IDE or GitHub these codeblocks don't get formatted :slightly_frowning_face:

This PR seems to have the same conflict as #1318. I was able to resolve that one by rebasing on upstream/master. I had to address conflicts in the docs/Makefile, sidenav.html, and banner.html files.

This isn't urgent so we can deal with when you're back.

**Comment by lucperkins** [comment]
Yeah, that’s indeed a bummer. There might be a way to have our cake and eat it too. Will explore when I’m back.

**Comment by lucperkins** [comment]
@tsandall I figured out a way to make it work with the side-by-side code panels but not with the line numbers. I don't think there's a way to have it both ways there.

**Comment by tsandall** [comment]
@patrick-east can you take a look at this?

**Comment by patrick-east** [comment]
Sorry for the delay, just catching up on reviews.

I like the pane shortcode, it still renders kinda funky in the markdown previews but the content at least shows as expected.

Echoing the concern raised by @tsandall i'm not a fan of the line numbers one that makes the preview show up like:

image

Which isn't ideal. I would lean towards sticking to the normal markdown syntax and the hugo/blackfriday generated `<pre><code>..` snippets and then using some javascript to do the line numbers as needed (it doesn't seem like we have a ton of spots we need them).

**Comment by lucperkins** [comment]
@patrick-east Unfortunately, I don't really see a way to accomplish what you're asking for. Hugo's [`highlight`](https://gohugo.io/content-management/syntax-highlighting) shortcode requires you to specify the language as a shortcode parameter. It can't infer the language from the inner content.

The JavaScript solution would be the only way to accomplish this in the way you're hoping for, but I don't have the chops for that.

**Comment by patrick-east** [comment]
Agreed, we would need to use some javascript (maybe a lib like prism.js or custom make something).

One thing I'm wondering is how much we really need the line numbers anyway. Is the intention mainly to replace the hard coded ones in this guide? Or do we want to add the line numbers to all our larger code snippets?

If it is only for a couple of spots like in this guide maybe we just reword the guide to work without the numbers?

**Comment by lucperkins** [comment]
@patrick-east I basically added this in an effort to provide feature parity with [GitBook](https://gitbook.io). It's a "nice to have" and not a big priority, so I'll close this for now and we can re-open if we want to tackle this later.

**Pull request closed without merging**
