### PR TITLE
[docs] Add intro text to Ecosystem sections

### PR DESCRIPTION
**Pull request by charlieegan3**
Before 
Screenshot 2023-08-31 at 11 04 43

After
Screenshot 2023-08-31 at 11 04 33

### CODE REVIEW

**Review by srenatus — APPROVED** [review]
Thanks!

**Comment by srenatus** [comment]
I believe that at some point, we'll need to do something about contrast there. Bold white on light teal is maybe acceptable, but the regular text is a little hard to read 👓

**Comment by charlieegan3** [comment]
Yeah, it's true... Perhaps this is better?

Screenshot 2023-08-31 at 11 23 40

**Comment by srenatus** [comment]
Oh yes I find that much better. What do you think?

**Comment by charlieegan3** [comment]
Yeah I think it's better. I've updated the branch to use that now

**Review by srenatus — APPROVED** [review]
Thanks a lot! 🎉

**Pull request merged**
