### PR TITLE
opa-wasm-builder: bump wabt, add binaryen

### PR DESCRIPTION
**Pull request by srenatus**
Some smaller changes to the wasm-builder docker image:

- wabt: bump to latest release
- binaryen: add

We're also bumping the builder version for this.

### CODE REVIEW

**Comment by srenatus** [comment]
The built opa.wasm differs, it seems, only because the producer custom section now reflects a version bump in the ubuntu distro packages for llvm 11:

### openpolicyagent/opa-wasm-builder:1.2:

```
Ubuntu clang version 11.0.0-++20201021094914+176249bd673-1~exp1~20201021075533.113
```

### openpolicyagent/opa-wasm-builder:1.3 (this PR):

```
Ubuntu clang version 11.1.0-++20210112083037+9bbcb554cdbf-1~exp1~20210112193657.159
```

**Comment by srenatus** [comment]
👀 so, the failures are expected, I suppose: `Error: The action has timed out.` ⌛ Until the image is pushed, it'll be built inside the PR checks, and it obviously takes too long...

**Comment by srenatus** [comment]
I guess if we're OK with this change, [this post-merge action](https://github.com/open-policy-agent/opa/blob/375120062da049c8a533dcd3f8b48222c677cf91/.github/workflows/post-merge.yaml#L96-L111) should update the image in dockerhub. It's hard to tell if the change is OK given the CI state, anyways. Maybe someone could built it themselves during review? 😃

**Comment by srenatus** [comment]
OK, better safe than sorry: I've run the github actions with the image pushed to my dockerhub repo, here: https://github.com/open-policy-agent/opa/actions/runs/530827177

It's all green. So I'll drop that commit and vote for admin-merging this PR 😉

**Review by tsandall — APPROVED** [review]
LGTM. Thanks for verifying the difference between opa.wasm outputs.

**Comment by srenatus** [comment]
Admin-merged because it had failed with a timeout, see comments above ☝️

**Pull request merged**
