### PR TITLE
docs/website: move apisix image to correct location

### PR DESCRIPTION
**Pull request by yzeng25**
Signed-off-by: yilin <yzeng25@wisc.edu>

Move Apache APISIX logo to `./website/static/img/logos/integrations/my-cool-integration.png` to show the actual logo.

Ref: https://github.com/open-policy-agent/opa/tree/main/docs#logos

image

### CODE REVIEW

**Comment by anderseknert** [comment]
Ouch! Can't believe I missed that. Thanks for double checking 👍

**Comment by yzeng25** [comment]
> Ouch! Can't believe I missed that. Thanks for double checking 👍

Done, it should show up now :)

**Comment by srenatus** [comment]
Huh? I have definitely seen the proper logo in the netlify preview. Weird.

**Comment by srenatus** [comment]
Just checked, it was some intermediate deployment where it had worked; not the one we ended up merging. This looks good, though.

**Review by srenatus — APPROVED** [review]

**Pull request merged**
