### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by deining**

### CODE REVIEW

**Review by srenatus — APPROVED** [review]
Thanks a lot!

**Comment by srenatus** [comment]
Please have a look at the DCO requirements -- they aren't met right now: https://github.com/StyraInc/fetchdb/commit/0af7ffa17701329058416257220febae69549297#diff-c79eae79a3498e3b75c9a0b5f581705567bf3b5e56acba47c2cb29add225df3aR119

With that fixed, we can merge this. 👍

**Comment by deining** [comment]
> Please have a look at the DCO requirements -- they aren't met right now: [StyraInc/fetchdb@0af7ffa#diff-c79eae79a3498e3b75c9a0b5f581705567bf3b5e56acba47c2cb29add225df3aR119](https://github.com/StyraInc/fetchdb/commit/0af7ffa17701329058416257220febae69549297#diff-c79eae79a3498e3b75c9a0b5f581705567bf3b5e56acba47c2cb29add225df3aR119)

DCO requirements are met now.

**Review by anderseknert — APPROVED** [review]
Thanks!

**Pull request merged**
