### PR TITLE
topdown: Add base64.verify builtin

### PR DESCRIPTION
**Pull request by carlpett**
Adds a builtin to verify a string is valid base64. Since it just covers base64, this is perhaps more of a start on #2690 than a full fix, for now, to verify (hah!) that I'm on the right way.
If everything looks good, I can add base64url, urlquery, json and yaml.

### CODE REVIEW

**Comment by tsandall** [comment]
@carlpett thanks for submitting a PR. Normally we'd just accept this since built-in functions are generally uncontroversial, however, in this case, I'm curious how urgently you require the fix--the reason is that we have another open issue that we're planning to work on that would _eventually_ resolve the entire class of problem (#2086).

If we fixed #2086 and made built-in errors undefined instead of halting evaluation then you could simply call `base64.decode` without worrying (or you could say `not base64.decode("...")` to check if the string was invalid. This approach would be much better than adding separate "verify" functions for each and every operation that requires it.

**Comment by carlpett** [comment]
Well, we have some policies that error out instead of failing "properly", but I wouldn't say it's the end of the world to wait a while if you believe that solution is better.
To some extent I'd argue that it's semantically clearer with a distinct verify function, though. It's very clear that we don't care about the actual decoded value, just that it is valid, as compared to `base64.decode("...")` which looks odd without using the result (to me, at least). Of course naming of the policy and the surrounding context will of course help reduce the risk of misunderstandings. Whether this is worth having extra functions for is the question, I guess :)

**Comment by tsandall** [comment]
hey @carlpett, your point about a separate function being clearer is fair. Could you rename this function to `base64.is_valid` instead of `base64.verify`? That will make it consistent w/ other similar built-in functions like `semver.is_valid` and `regex.is_valid`. If you make that change, we can merge this PR.

**Comment by carlpett** [comment]
Ah, didn't see those ones. I'll rename to match!

**Review by tsandall — APPROVED** [review]
LGTM

**Comment by zenmatic** [comment]
should `base64.is_valid()` appear in the docs in https://www.openpolicyagent.org/docs/latest/policy-reference/?  I don't see it.

**Comment by anderseknert** [comment]
Hmm yeah, doesn't look like that got included in the PR. Would you want to add it to the docs, @zenmatic?

**Pull request merged**
