### PR TITLE
build: Add static image variant

### LINKED ISSUE #3633: Introduce image variant containing the statically linked OPA binary
We currently only publish the statically linked OPA binary to GitHub releases. In some cases, it would be nice to distribute the same binary via Docker images (e.g., for users that have to import the artifact into an internal repo.)

Image variant name: `static`

Example:

```
openpolicyagent/opa:0.32.0-static
```

### PR DESCRIPTION
**Pull request by tsandall**
Fixes #3633

Signed-off-by: Torin Sandall <torinsandall@gmail.com>

### CODE REVIEW

**Comment by tsandall** [comment]
@srenatus I think this is quite safe but if you could take a close look that would be great.

**Comment by srenatus** [comment]
Changes look good but I'll play with it a bit, too.

**Comment by srenatus** [comment]
I guess we could run into TLS trouble with the scratch image. Something like https://gist.github.com/michaelboke/564bf96f7331f35f1716b59984befc50 or using another distroless base would do the trick.

**Comment by srenatus** [comment]
Let's change the base image. With `scratch`, I get:

```
$ docker run docker.io/openpolicyagent/opa:0.31.0-dev-static eval 'http.send({"url": "https://httpbin.org/json", "method": "get"})' --strict-builtin-errors
{
  "errors": [
    {
      "message": "http.send: Get \"https://httpbin.org/json\": x509: certificate signed by unknown authority",
      "code": "eval_builtin_error",
      "location": {
        "file": "",
        "row": 1,
        "col": 1
      }
    }
  ]
}
```

Using [`gcr.io/distroless/static`](https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md) instead, it works.

I suppose the expectation when using the -static image would be that anything not depending on glibc _works_... 🤔

**Comment by tsandall** [comment]
I'm fine with using gcr.io/distroless/static as the base. The goal here is not to produce the minimal Docker image containing an OPA binary. As long as we provide the OPA binary, we're good.

**Review by srenatus — APPROVED** [review]

**Pull request merged**
