### PR TITLE
Update OPA Support page to include PACLabs as a support organization

### PR DESCRIPTION
**Pull request by johndbro1**
### Why the changes in this PR are needed?

I want to update the support page for OPA to include PACLabs, my consulting company.  (https://paclabs.io)

### What are the changes in this PR?

I have updated the website page: support/list.html to include PACLabs, and I've added the logo to the static/img/logos/ directory.

### Notes to assist PR review:

Anders Eknert told me that this was the best move to have the web page updated.

### Further comments:

Netlify preview:   https://64e4df5f812ebf266daf1741--inspiring-zabaione-70a5dc.netlify.app/support/

### CODE REVIEW

**Comment by ashutosh-narkar** [comment]
@johndbro1 thanks for filing this PR. It would be more helpful and relevant for the OPA community if Pac Labs pointed to a dedicated support page that clearly stated the kind of support and services that y'all are offering. Your front page has some of that but the community I think would be greatly benefit if there was specific content related to products and services for OPA in one place. Hope that helps. Thanks!

**Comment by johndbro1** [comment]
Fair enough.  I've added the OPA and OPA-related services into a dedicated support page for OPA on our site.  Let me know what you think

**Comment by johndbro1** [comment]
I don't know how to do that.  Should I just kill this whole PR and start over?

**Comment by ashutosh-narkar** [comment]
> I don't know how to do that. Should I just kill this whole PR and start over?

Sure. Make sure you pull in all the latest changes before you add your changes.

**Pull request closed without merging**
