### PR TITLE
Change maintainers for Gatekeeper

### PR DESCRIPTION
**Pull request by maxsmythe**
Move Will Beason to emeritus status, add Ernest as a maintainer.

Looks like this needs a 2/3 vote at the organization level.

https://github.com/open-policy-agent/opa/blob/main/GOVERNANCE.md#changes-in-maintainership

### CODE REVIEW

**Review by maxsmythe — COMMENTED** [review]
LGTM

**Review by ritazh — APPROVED** [review]
+1

**Comment by tsandall** [comment]
+1

**Comment by willbeason** [comment]
❤️

**Pull request merged**
