### PR TITLE
fix: broken links after renaming pam_authz to pam_opa

### PR DESCRIPTION
**Pull request by j-zimnowoda**

### CODE REVIEW

**Review by anderseknert — APPROVED** [review]
Thanks!

**Comment by anderseknert** [comment]
For this to be merged you'll need to add your signature to the commit. See https://github.com/open-policy-agent/opa/blob/master/CONTRIBUTING.md#developer-certificate-of-origin

**Review by srenatus — APPROVED** [review]
👏 thanks

**Comment by anderseknert** [comment]
@j-zimnowoda as soon as you have fixed the DCO we'll have this merged. See my previous comment.

**Comment by tsandall** [comment]
hey @j-zimnowoda if you can sign-off on the changes, we'll merge this!

**Comment by tsandall** [comment]
Closing this PR as it's been open for over a month. We can always re-open once the DCO can be signed.

**Pull request closed without merging**
