### PR TITLE
docs: Add links to homepage

### PR DESCRIPTION
**Pull request by timothyhinrichs**
Previously, there were no links from the homepage to any of the
more detailed docs about use cases and even mention of use cases
was below the fold.

This change adds links to use cases at the very top of the page,
along with pointers to core docs and the OPA summit.

Signed-off-by: Tim Hinrichs <tim@styra.com>

### CODE REVIEW

**Comment by patrick-east** [comment]
Love the idea, and the desktop version looks pretty good. I opened this up on my phone initially and I think we'll need to tweak some of the css or something to make it fit better on mobile sized layouts 
Screenshot_20190830-213143

I can play around with it if you'd like.

**Comment by timothyhinrichs** [comment]
If you could play with it, that'd be great!

Tim

**Comment by patrick-east** [comment]
I was messing around with this to make the mobile layout fit a little more smoothly. In the process I've had a few questions arise:

1) If we do this, why keep the use-case sections below? Should we move the diagrams (where applicable) to the landing pages for each use-case in the doc content?
 My reasoning is that if we have quick links like this that will be in the viewport, is there any reason someone would scroll down to the other ones?
1) If we do keep the use-case stuff below the fold should these links point to sections down there, and in each of them we link to the detailed docs?
1) Should we update the top nav bar that has "Documentation" and "Tutorials" on it? We will kind of have duplicate links now quickly accessible. It might make sense to put links to the top level use cases like "Kubernetes" or something up there too? Or just remove them in favor of the ones in the middle of the screen and only keep the playground and support ones?
1) Would it make sense to put these top level almost ToC or like doc entry points into a landing page on https://www.openpolicyagent.org/docs/latest rather than that page being the OPA introduction? (which we could move to like https://www.openpolicyagent.org/docs/latest/introduction or something)

**Comment by patrick-east** [comment]
Closing in favor of #1741 

@timothyhinrichs check it out when you have a chance, I think that version lines up pretty closely with what @tsandall sketched up.

**Pull request closed without merging**
