### PR TITLE
change input type for concat

### PR DESCRIPTION
**Pull request by sunjh**
### Why the changes in this PR are needed?
This is to improve the concat function mentioned here [https://github.com/open-policy-agent/opa/issues/6911](ISSUE 6911)

### What are the changes in this PR?
Changed concat to accept both string & number

### Notes to assist PR review:
#6911

### CODE REVIEW

**Comment by sunjh** [comment]
Hi @anderseknert looks like it passed all the checks, please help review it, thanks!

**Comment by srenatus** [comment]
Code looks good. An extra test in the yaml test cases would be a nice touch. I'm also afraid this won't work as-is with wasm 🤔

**Comment by sunjh** [comment]
> Code looks good. An extra test in the yaml test cases would be a nice touch. I'm also afraid this won't work as-is with wasm 🤔

Thanks @srenatus , I will try to add an extra test case for this.
Since I'm not using wasm, not familiar with it, would you mind share some docs about how to verify that in wasm? Thanks!

**Comment by srenatus** [comment]
So as soon as we have a yaml tests case, the CI suite will run that yaml test case with standard eval (topdown) and wasm; and both tests need to succeed for the PR to go green.

Concretely, we'll need the same change you've done here for topdown in the wasm "base lib", which is a few C functions here: 
- https://github.com/open-policy-agent/opa/blob/main/wasm/src/strings.c#L228-L233
- https://github.com/open-policy-agent/opa/blob/main/wasm/src/strings.c#L252

**Comment by sunjh** [comment]
> So as soon as we have a yaml tests case, the CI suite will run that yaml test case with standard eval (topdown) and wasm; and both tests need to succeed for the PR to go green.
> 
> Concretely, we'll need the same change you've done here for topdown in the wasm "base lib", which is a few C functions here:
> 
> * https://github.com/open-policy-agent/opa/blob/main/wasm/src/strings.c#L228-L233
> * https://github.com/open-policy-agent/opa/blob/main/wasm/src/strings.c#L252

Thanks for the comments. Working on it.

**Comment by ashutosh-narkar** [comment]
@sunjh thanks for working on this.  Just checking in to see if you had a chance to address Stephan's comments. We can then get this in the next release.

**Comment by ashutosh-narkar** [comment]
@sunjh closing this PR for now. Feel free to re-open when you get a chance to address the PR comments and we can get this in.

**Comment by sunjh** [comment]
Sorry for the late response @ashutosh-narkar , lots of things going on here recently. And based on the policy of my organization, I cannot continue working on this any more. Please feel free to assign this task to others. 

Thanks.

**Pull request closed without merging**
