### PR TITLE
Added DisableKeepAlives = true to the rest_auth.go file to fix #4884

### LINKED ISSUE #4884: Disable HTTP keep-alives for the OPA rest client
## What is the underlying problem you're trying to solve?
Frequently pulling bundles, in certain cases, keeps a large number of connections open in OPA instances.

## Describe the ideal solution
Identify under what scenario(s) are preventing such connections from closing.

## Describe a "Good Enough" solution
Disabling HTTP keep-alives for the OPA rest-client can reduce the number of idle connections staying open for an extended period of time.

### PR DESCRIPTION
**Pull request by Parsifal-M**
Signed-off-by: Peter Macdonald <macdonald.peter90@gmail.com>

Hi @ashutosh-narkar, is this more or less what you had imagined for this? It seems like a very simple fix so I thought I would just try it out.

Please let me know? Also by way of testing, do we need to/have an approach to test this?

Thanks!

### CODE REVIEW

**Comment by ashutosh-narkar** [comment]
Thanks for adding the fix. To test this you could create a local bundle server and then have OPA frequently fetch bundles from it. Then observe number of open connections via something like `netstat`. You should see a difference in the number of `ESTABLISHED` connections before and after the fix.

**Comment by Parsifal-M** [comment]
Hey @ashutosh-narkar 

Just checking, is it okay if I test this on localhost? I am just building a couple of bundles then running the below, is this approach ok?

```
 opa run --server \
    --set bundles.example.resource=bundle.tar.gz \
    --set services.example.url=http://localhost:8080
```

and then

```
python3 -m http.server --bind localhost 8080
```

Then running `netstat`

**Comment by ashutosh-narkar** [comment]
> Just checking, is it okay if I test this on localhost? 

Yes should be fine. Thanks!

**Comment by ashutosh-narkar** [comment]
@Parsifal-M let's close this for now. We can come back to this once we've had a good idea how to verify this change works as expected. Feel free to pick this up if you get a chance to create a test case(s) to verify this. Thanks for looking into this.

**Pull request closed without merging**
