### PR TITLE
Add basic out-of-band metrics collection

### PR DESCRIPTION
**Pull request by rlguarino**
Collect Duration metrics form the http handlers. Instrument each handler
using the promhttp package. The metrics are partitioned on their status code,
the name of the handler serving the request and the HTTP method, as
"code", "handler" and "method" respectively.

To avoid unbounded cardinality an approximation of the request's url is
used as the "handler" dimension. The handlers roughly correspond to the
different api resource path & the api version.

Issue: #525

Signed-off-by: Ross Guarino <rssguar@gmail.com>

### CODE REVIEW

**Comment by rlguarino** [comment]
I don't really like how large of a change this is, is there a way for me to make the changes to vendor less large? I followed the guide form the [development.md](https://github.com/open-policy-agent/opa/blob/master/docs/devel/DEVELOPMENT.md) file which said to run `glide update --strip-vedor` but it seems to have done more than just add the Prometheus package.

**Comment by tsandall** [comment]
@rlguarino the vendoring is OK. I don't think there's a way to get Glide to do the update at a finer granularity.

**Comment by tsandall** [comment]
These changes are nicely self-contained! I'm going to pull down the branch and test it out. Pending any glaring issues, we can merge this.

**Comment by tsandall** [comment]
OK, no problems testing the changes manually. I debugged the test failure and found that there appears to be an issue in the prometheus go client. I've submitted a PR to fix that (https://github.com/prometheus/client_golang/pull/373). Once they merge, you can revendor and the test should start passing.

**Comment by rlguarino** [comment]
Thanks @tsandall  so much for helping with this.

**Comment by tsandall** [comment]
LGTM!

**Pull request merged**
