### PR TITLE
chore: Replace ghodss/yaml with sigs.k8s.io/yaml

### PR DESCRIPTION
**Pull request by mrueg**
### Why the changes in this PR are needed?

ghodss/yaml hasn't seen any commits since 2019 (the last one was a change in README), sigs.k8s.io/yaml is a more recent and more active fork supported by the kubernetes community. 
https://github.com/kubernetes-sigs/yaml

### What are the changes in this PR?

Migrate dependency from ghodss/yaml to sigs.k8s.io/yaml

### Further comments:

Here's a similar change that got included in gatekeeper already:
https://github.com/open-policy-agent/gatekeeper/pull/2697

### CODE REVIEW

**Comment by anderseknert** [comment]
Hi there! And thanks. https://github.com/open-policy-agent/opa/issues/5754 provides some context forward this hasn’t been considered too important in the past. Do you know if the issue described there is solved now? I’m on mobile so I can’t easily see until later :)

**Comment by mrueg** [comment]
@anderseknert :wave:  thanks for the context, I wasn't aware that there's an issue already! I'll take a look tomorrow and see if this change is able to fix the issue as well.

**Comment by anderseknert** [comment]
Just to be clear, I didn’t mean we shouldn’t merge this if not. But whatever we use would  be temporary until we have a something addressing those issues.

**Comment by mrueg** [comment]
The issue #5754 is not fixed by this change but likely will be if https://github.com/kubernetes-sigs/yaml/pull/76 is merged into the upstream repository.

**Review by anderseknert — APPROVED** [review]
LGTM

**Pull request merged**
