### PR TITLE
wasm: Add support for parsing and dumping set literals

### LINKED ISSUE #2773: wasm: Allow host to send and receive sets
Currently the caller can only send and receive JSON values. As a result, sets are not supported in the base `input` or `data` documents and built-in functions cannot accept or return them either. This causes issue for built-in functions like `net.cidr_contains_matches` which can receive sets or arrays as input.

### PR DESCRIPTION
**Pull request by tsandall**
This commit adds support into the C library for parsing and dumping
set literals without representing them as arrays (we use the Rego
convention of curly-braces and set() for emptiness.) The parsing and
dumping that supports set literals is exposed via new opa_value_parse
and opa_value_dump functions (respectively).

Fixes #2773

### CODE REVIEW

**Comment by tsandall** [comment]
One thing I realized while working on this PR was that the parser doesn't free up memory if an error occurs. I don't think this is a huge issue (since a parsing error will likely halt evaluation) but it's something we should be aware of.

**Review by patrick-east — DISMISSED** [review]
LGTM. Should we add these to the docs? Thinking like this table: https://www.openpolicyagent.org/docs/latest/wasm/#exports

**Comment by patrick-east** [comment]
> One thing I realized while working on this PR was that the parser doesn't free up memory if an error occurs. I don't think this is a huge issue (since a parsing error will likely halt evaluation) but it's something we should be aware of.

At some point we'll probably have to deal with some of that, especially for the like long(ish) running wasm instances like what we're planning for the server integration. Hard to say how much it matters right now though.

**Comment by tsandall** [comment]
@patrick-east good catch on the docs. Updated to include `opa_value_parse` and `opa_value_dump`. Also mentioned that `opa_json_dump` serializes set values as JSON arrays.

**Pull request merged**
